### ISSUE TITLE
Windows default multipass folder

### ISSUE THREAD

**Issue by zd-dalibor** [canonical/multipass#1112]
Is there any way to change default folder location (folder where multipass download and keep vm images, vm disks, caches etc.) on windows. I do not have enough space on `c:\` drive. It will be nice that there is some env variable or config for changing default folder location.

**Comment by Saviq** [comment]
Hi @zd-dalibor, unfortunately not at the moment, but I'll mention #756 for us to remember to add this option.

Thanks!

**Comment by Saviq** [comment]
@zd-dalibor in the mean time, I wonder if you could try your luck with [Windows link files](https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/) - our files go into `C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd`

**Comment by flash-me** [comment]
This would be a great feature. 
Also this would mean that we could change the location to a directory that does not require admin permissions.

**Comment by beppler** [comment]
The current folder location causes problems on Windows when upgrading versions too, see #1012 and #1119.

The best folder to put this kind of application data on Windows is inside C:\ProgramData.

**Comment by Saviq** [comment]
@tatroc replying here to keep the discussion in one place:

> When I create a VM via Multipass the VM gets created in the following location
> C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\vault\instances\foo
> 
> Consider using the default location setting for Hyper-V to store the files Hyper-V VM files
> C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks
> C:\ProgramData\Microsoft\Windows\Hyper-V

As you can see it's not unanimous what's the best location :)

Bearing in mind that Multipass has different backends, I would stay away from Hyper-V specific folders and go into `ProgramData` indeed. There's [a powershell command](https://stackoverflow.com/questions/11196151/win32-function-to-get-path-to-c-programdata) to get its location it seems like.

**Comment by beppler** [comment]
I think that the code of daemonconfig.cpp on lines [74](https://github.com/canonical/multipass/blob/master/src/daemon/daemon_config.cpp#L74) and [76](https://github.com/canonical/multipass/blob/master/src/daemon/daemon_config.cpp#L76) can be altered to the second item of the [QStandardPaths::standardLocations](https://doc.qt.io/qt-5/qstandardpaths.html#standardLocations) method instead of .[QStandardPaths::writableLocation](https://doc.qt.io/qt-5/qstandardpaths.html#writableLocation)

This method is [documented](https://doc.qt.io/qt-5/qstandardpaths.html#StandardLocation-enum) to return "/usr/local/share/<APPNAME>" on Linux, "/Library/Application Support/<APPNAME>" on MacOS and "C:/ProgramData/<APPNAME>" on Windows.

So the files will be create on a directory that is not subject to be remove on Windows upgrades as reported on #1012 and #1119.

**Comment by Saviq** [comment]
While this may very well be a documentation bug, those docs also say:
```
The following table gives examples of paths on different operating systems. The first path is the writable path (unless noted). Other, additional paths, if any, represent non-writable locations.
```

So using those as writable would be going against that…

**Comment by beppler** [comment]
Yes, but the installer can grant the required permissions to the user that is used to run the daemon to write on those locations.

Maybe this should be used only on Windows so #1012 and #1119 will be resolved and the files start to be written on a easier place to find.


> While this may very well be a documentation bug, those docs also say:
> 
> > The following table gives examples of paths on different operating systems. The first path is the writable path (unless noted). Other, additional paths, if any, represent non-writable locations.
> 
> So using those as writable would be going against that…

**Comment by Saviq** [comment]
> Yes, but the installer can grant the required permissions to the user that is used to run the daemon to write on those locations.
> 
> Maybe this should be used only on Windows so #1012 and #1119 will be resolved and the files start to be written on a easier place to find.

Sure, I'm not saying it's a wrong location to use - rather that using the Qt API might be wrong, in case they ever change to not have that folder as the second location.

**Comment by ascarter** [comment]
In the Hyper-V case, there is specific configuration for setting the location of the VM's and the disk files. It would be ideal if multipass honored those settings. I believe Virtual Box has similar settings.

![image](https://user-images.githubusercontent.com/4931/72669501-3523f900-39e7-11ea-9ce6-9cfcaf0320fd.png)

**Comment by beppler** [comment]
I think that this is the same kind of problem reported on #566.

The use of Qt API here is harming the use of the tool on Windows.

All my instances are lost almost every time a new Windows version is released because this directory is not migrated to new version.

One option is having an configuration option to specify the directory (again it can be set during installation).

Another option modify the installer to create a new account and use it to run the daemon (adding it to the right groups), so the images will be stored on C:\Users\username\..., not inside the Windows directory.

**Comment by ffimnsr** [comment]
Just updated my Windows 10 to build 2004 just this week and noticed that the multipass instances and mapping all been deleted 
Hopefully this feature would be implemented

**Comment by trollcop** [comment]
Is anything going to be done about this? 

Keeping all this stuff on C: and *especially* out of users's reach behind systemprofile account is outrageous.

Many users may have a dedicated drive for VMs or not enough space on C: to host 100s of gigabytes of VMs etc.

Many valid options were proposed, something that ends up in %appdata% by default would be great, or even better, offer VM/metadata/image location during installer just like when asking for install folder. For example I placed my install into d:\programs\multipass and found that it started eating up space on C: downloading an image, and it took several tries of googling to arrive to this page to find out that all VM/metadata is stored in some inaccessible folder on C:

**Comment by mconner** [comment]
I had a workaround that involved moving the vm through hyper-v manager, but I just found that [release 1.5.0](https://github.com/canonical/multipass/releases/tag/v1.5.0) includes support for defining MULTIPASS_STORAGE.  If you look at the pull, it has instructions for use, Here's the [one for windows](https://github.com/canonical/multipass/pull/1789#issuecomment-705403501) .  

It seems like this covers this issue, so perhaps this issue should be closed?

**Comment by Saviq** [comment]
Well, -ish, this issue is about where we put the data by default, we still have to fix that. And when doing that, migrate data from the previous location, which `MULTIPASS_STORAGE` handling, explicitly, doesn't do.

**Comment by mconner** [comment]
@Saviq: While the title is "Windows default multipass folder",   what the issue creator, @zd-dalibor, is requesting is the ability to _define_ the location:   
> I do{1} have enough space on c:\ drive. It will be nice that there is some env variable or config for changing default folder location.

_{1} (I assume he meant "do not", or this makes no sense.)_

Since there's been no way -- till now -- to do this, "default" multipass folder in this context isn't relevant. Its just "the" multipass folder.

While settling on a better default (when MULTIPASS_STORAGE is not set) would be useful, its not what he was asking for.  He was asking for "some env variable or config", which is what MULTIPASS_STORAGE is.

That said, it would make sense to create new issues:
- Defining the default storage location.  (btw: why not use the mutipass install dir?)
- Migrating existing data if someone changes the multipass storage location after the fact.
- Change the installer to allow the user to pick the storage location (My suggestion)

Just a though.

**Comment by ginomessmer** [comment]
> Keeping all this stuff on C: and especially out of users's reach behind systemprofile account is outrageous.

I just witnessed this issue and can second this. It is really outrageous. In my case, I store all my VM disks and images on a secondary drive since my C: SSD is being used for other purposes (also it's running low on storage if loads of VM disks are stored there anyway...). 

Ultimately, I ended up uninstalling Multipass since its storage behavior doesn't make the cut for me right now.

**Comment by mconner** [comment]
> Ultimately, I ended up uninstalling Multipass since its storage behavior doesn't make the cut for me right now.
@ginomessmer If you note my comment from last week, It looks like they've solved this with MULTIPASS_STORAGE in release 1.5

**Comment by ginomessmer** [comment]
Oh, thank you for the heads up @mconner, I did not notice. My bad, will give it a second shot then.

**Comment by trollcop** [comment]
The default VM folder should be an option during install, and NOT default
to a protected location a user cannot access. Having some obscure variable
post install and no reasonable way to move the stuff is still not an
acceptable end user solution.

**Comment by NatsumiHB** [comment]
Just wanted to check out Multipass and found this while trying to find a way on how to change the default folder for new Multipass VMs. Since this is not possible and I don't have much space on my C: drive I might actually have to manually set up VMs.

**Comment by Saviq** [comment]
@NatsumiHB if you read up, and in [the 1.5.0 release notes](https://github.com/canonical/multipass/releases/v1.5.0), you can use the `MULTIPASS_STORAGE` variable to change where the VMs go.

**Comment by NatsumiHB** [comment]
> @NatsumiHB if you read up, and in [the 1.5.0 release notes](https://github.com/canonical/multipass/releases/v1.5.0), you can use the `MULTIPASS_STORAGE` variable to change where the VMs go.

Thanks for the tip and I appreciate that you folks will make it an option in the installer.

**Comment by kragil** [comment]
Putting stuff in C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\virtualbox\vault\instances\primary

is really uncommon. That must be an option in the installer. Nobody will find it there. Trust me ;-)

**Comment by devspyrosv** [comment]
> 
> 
> > > Putting stuff in C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd\virtualbox\vault\instances\primary
> > > is really uncommon. That must be an option in the installer. Nobody will find it there. Trust me ;-)
> > 
> > 
> > Not only is it _uncommon_ that folder is completely _inaccessible_ to normal users of the system without assuming ownership.
> > That is _completely_ unacceptable. And yeah I've stopped using multipass stuff completely simply because there is no way to manage storage location for VMs.
> 
> @kragil and @trollcop: (Given your name, I'm not sure I should be replying.), I will point out (again): There _is_ a way to manage storage, at least to a limited extent, in that you can set MULTIPASS_STORAGE, per [this comment](https://github.com/canonical/multipass/pull/1789#issuecomment-705403501). And while it may be a [workaround](https://github.com/canonical/multipass/issues/1112#issuecomment-728187752), it may meet your needs.

By using the  MULTIPASS_STORAGE workaround, I get VMs with strange partitioning and / dirs of many GBs less than the disk size I provide through args. This happens in win10, multipass 1.6.2 with Hyper-V

**Comment by polarapfel** [comment]
As a workaround for myself, I have just deleted the "instances" folder and replaced it with a symbolic link to a data drive with more space. If that helps anyone. Works fine.

**Comment by Dragon201701** [comment]
> @zd-dalibor in the mean time, I wonder if you could try your luck with [Windows link files](https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/) - our files go into `C:\Windows\System32\config\systemprofile\AppData\Roaming\multipassd`.

`C:\Windows\System32\config\systemprofile\AppData\Roaming>mklink /D "C:\Windows\System32\Config\Systemprofile\AppData\Roaming\multipassd" "D:\multipassd"
symbolic link created for C:\Windows\System32\Config\Systemprofile\AppData\Roaming\multipassd <<===>> D:\multipassd` 

That's my solution

**Comment by bscottm** [comment]
I just bumped into this problem as well. For me, the `C:\Windows\System32\config` directory ends up being inaccessible. "+1" for relocating it elsewhere.

**Comment by FH-Inway** [comment]
Also ran into issues with the default directory for vms created by multipass. +1 for providing a better location.

**Comment by kajeagentspi** [comment]
Got my dev setup wiped by upgrading to Windows 11.

**Comment by trollcop** [comment]
> Got my dev setup wiped by upgrading to Windows 11.

This bug has been here since 2019, and they still haven't fixed it. Amazing.

**Comment by kajeagentspi** [comment]
> > Got my dev setup wiped by upgrading to Windows 11.
> 
> This bug has been here since 2019, and they still haven't fixed it. Amazing.

Honestly I don't know why the files are inside the Windows folder when this isn't a Windows project.

For those that upgraded to Windows 11 you should able to find your files by changing Windows to Windows.old on the path from Hyper-v. I can't do this since I already deleted Windows.old.
