### ISSUE TITLE
Skip image resize if the default is too small

### ISSUE THREAD

**Issue by paride** [canonical/multipass#1139]
Following the instructions in [1] I can successfully launch Fedora cloud images distributed at [2] using multipass:
```
$ multipass launch -n paride-fedora file:///home/paride/Fedora-Cloud-Base-30-1.2.x86_64.qcow2
Launched: paride-fedora

$ multipass exec paride-fedora cat /etc/os-release
NAME=Fedora
VERSION="30 (Cloud Edition)"
[...]
```
however I can't launch CentOS 7 instances using the CentOS cloud images [3]:
```
$ multipass launch -vvv -n paride-centos file:///home/paride/CentOS-7-x86_64-GenericCloud.qcow2
launch failed: Cannot resize instance image
```
This while running the multipass snap 0.8.1/1230 on an up-to-date amd64 Eoan system. Let me know if you need any other detail. Thanks!

[1] https://discourse.ubuntu.com/t/new-way-to-launch-images-other-than-cloud-images-from-simplestreams/6282
[2] https://alt.fedoraproject.org/cloud/
[3] https://cloud.centos.org/centos/7/images/

**Comment by Saviq** [comment]
Hi @paride do the CentOS images have `cloud-init` set up? There's no other way we can inject ourselves into the VM.

**Comment by ricab** [comment]
Hi @paride, this error arises because the default disk size for instances (5G) is smaller than the minimum required with that image (8G). You can make it work by passing `--disk 8G` in the launch command.

There is a PR improving this error msg, so in a future release you'd see something like: `launch failed: Requested disk (5368709120 bytes) below minimum for this image (8589934592 bytes)`.

Perhaps we should consider deriving the default automatically in such cases...

**Comment by Saviq** [comment]
D'oh, should've read closer.

Indeed this works fine:
```
$ multipass launch --disk 10G https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
Launched: frisky-chicken
```

I will make this bug about the minimum disk image handling.

**Comment by paride** [comment]
I can confirm the workaround works. Thanks!
