### ISSUE TITLE
Multipass not compatible with Virtual Machine Platform feature needed for WSL 2 and the new Windows Terminal

### ISSUE THREAD

**Issue by davecore82** [canonical/multipass#1144]
When trying to launch an instance with multipass in Windows 10 Home edition with the virtualbox driver, the instance fails to launch:

```
C:\Users\dcoro>multipass start dutiful-boatbill
start failed: Could not start VM: Waiting for VM "dutiful-boatbill" to power on...
VBoxManage.exe: error:  (VERR_NEM_MISSING_KERNEL_API).
VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
```

Trying to launch virtual machines in VirtualBox directly without multipass also fail. The VT-x feature is enabled in BIOS. Running the Intel Processor Identification Utility also says that VT-x is not enabled. A quick investigation pointed me to the 'Virtual Machine Platform' optional component being enabled. That feature is necessary in Windows 10 for running WSL 2 (and subsequently the new Windows Terminal since it allows to run the various Linux command lines that come with WSL). When that feature is enabled, both VirtualBox and the Intel utility will fail to see that VT-x is enabled.

The new Windows Subsystem for Linux 2 (WSL 2) requires this Virtual Machine Platform feature:
https://docs.microsoft.com/en-us/windows/wsl/wsl2-install

I suspect the people wanting to run Multipass on their Windows devices might be among the same people that could be interested in using WSL 2. 

Could Multipass be made to support the 'Virtual Machine Platform' feature?

**Comment by Saviq** [comment]
Hi @davecore82, thanks for reporting.

Indeed VirtualBox is incompatible with Hyper-V (what's behind VMP), at least because it's running inside a VM already.

We'll have to understand how flexible VMP is to see if it's possible to use. Not saying no, but a lot needs to be determined.

**Comment by diddledan** [comment]
An alternative is to piggyback on the WSL2 system the way that docker has recently pivoted to: https://engineering.docker.com/2019/10/new-docker-desktop-wsl2-backend/

The idea being that the multipass daemon running on Windows builds and starts multipass systems via WSL2 instead of their own VM on Hyper-V or VirtualBox. This has the advantage that it will be supported on Windows 10 Home where Hyper-V isn't available, but WSL2 will be. Bonus points for coordinating with Snapcraft (cc: @sergiusens) to get that to talk with the Windows-based multipassd from the WSL2-based Linux distro for building snaps (also cc: @sirredbeard for WSL input).

**Comment by Saviq** [comment]
There are a handful of concerns about just sitting "on top" of WSL2:
- its integration with the host system, which may interfere with some use cases (think the same service running in multiple WSL2 containers)
- the kernel being run
- isolation between instances

We definitely want to be compatible with WSL2, so expect more in this space soon.

**Comment by townsend2010** [comment]
Virtualbox fixed this issue long ago and should no longer be a problem.
