### ISSUE TITLE
Support for bridged networking

### ISSUE THREAD

**Issue by gwatts** [canonical/multipass#118]
I often want to run services in a VM that are reachable from the local network.  The easiest way for me to do that is to use a bridged network interface, so that the VM appears to be directly on the LAN.

Are there any plans to add that kind of network interface?

**Comment by carmine** [comment]
I assume bridged networking is the same as host networking - ie the VM uses the same IP as the host?  If so, I'd like to vote for this feature too. 

It'll facilitate scenarios where an Application in the VM, accessed through a browser, does a redirection. I've come across this in a kubernetes setup .. port mapping / nat. Whereas this isn't specifically a multipass issue, presumably host networking would alleviate the pain point (the pain of finding another workaround).

**Comment by Saviq** [comment]
Not the same IP, but the same subnet, getting IPs from the same DHCP server. This could partially be achieved by forwarding ports on the host IP to ports in the instance - in this case you actually gain control over what's exposed vs. exposing all services from the instance.

**Comment by carmine** [comment]
The port forwarding works for kubernetes .. ie they have a networking concept called NodePort which exposes a port in the range of 30000-33000, or something like that.  With that, I can access the embedded jupyterhub. It's when I tell it to spawn something, and the ensuing redirect happens, that I get into trouble. I'll pose an example so that it is easier to see.

**Comment by Saviq** [comment]
I think with kubernetes we're getting into two levels of indirection - Multipass starts a virtual machine instance and then k8s starts containers inside? Which means there's three networks - host (your non-virtual physical/WiFi network), Multipass's subnet and then inside the VM, one more subnet for k8s. Even when k8s exposes something, it will expose it at most on the VM's IP, which is in a Multipass-private subnet.

This issue is about putting the Multipass instances on your physical network, "next to" your host. K8s would still use an internal network, but the services it would expose would be available to others on your physical network. Something similar can be achieved with port forwarding where services inside the Multipass-private subnet would be exposed on your host's IP, again making them available on your non-virtual network.

**Comment by popey** [comment]
Adding a +1 for this feature. I frequently spin up servers on VMs to test them, and want to access them from outside without having to do any port forwarding nonsense. Having the VM exposed on the LAN as if it were just another machine is the way I tend to use this.

**Comment by dhenrich** [comment]
Agreed. It's a common use case for developers and something I'd find really useful.

**Comment by hyzhak** [comment]
My case: I was trying to setup kubeflow on microk8s, which inside of multipass on my small local DL server. [Here is official instruction](https://www.kubeflow.org/docs/started/getting-started-multipass/), but because of this issue it didn't work well. I couldn't get access to the services of kubeflow (Jupyter, k8s dashboard, tf dashboard and etc). So it would great if multipass would give access from local network to any web app inside of multipass.

**Comment by kbknapp** [comment]
I'll add my use case to this.

At work we currently use LXD to spin up several containers on a separate bridge network creating a island of containers for a large testing infrastructure. Each container has two interfaces, one connected to the bridge with a private IP, and the other connected to the standard LXD `lxdbr0`. 

We do this several times, so end up with several islands of containers. We then use normal `brctl` to separate these bridges with VLAN tagging to keep these islands from talking directly over the network.

The end state (for two islands of 3 containres each):

* "island 1" containers can talk to each other, and to the host
* "island 2" containers can talk to each other, and to the host
* The islands can't talk to each other except through the host

This allows the host to simulate "the internet", and the islands to simulate private networks.

This all works great, except some of the tests are requiring full blown VMs instead of containers (since they need to mess with the kernel and such).

`multipass` would be a great solution to this problem so we could still take advantage of all the testing infrastructure automation. However, if we can't add additional networking interfaces and network bridges to `multipass` VMs (a la `lxc network create foobr0 && lxc config device add island-1-container eth1 nic nictype=bridged parent=foobr0 name=eth1`) it's not viable yet.
`

**Comment by Gnommer** [comment]
I have a case where I have to develop dockerized apps and I don't have access to windows 10 pro for (docker for windows). multipass seemed like a viable vm solution unlike other methods to make vms cause its light and fast. though on the windows build 1903 it seems the ipv4 address is not detected. and its shown as N/A. I am using virtualbox for the localdriver can any help me out on this ?

**Comment by Saviq** [comment]
Hi @Gnommer, yes VirtualBox's networking does not mimic a normal network segment, it all happens in a software router they implement. Which is why the IP is reported as N/A, because it's meaningless outside of the instance anyway.

Bridging is an option there, and we'll be looking at implementing it soon.

**Comment by v1k0d3n** [comment]
any updates @Saviq? I'm following, but not as closely as I'd like.

**Comment by Saviq** [comment]
Hey @v1k0d3n, I'm afraid it doesn't look like we'll get to this in the immediate future :/

**Comment by v1k0d3n** [comment]
@Saviq that's unfortunate. :(

![boo](https://media.giphy.com/media/EXHHMS9caoxAA/giphy.gif "sad dunk")

**Comment by richiethom** [comment]
It'd be really good to include this limitation in the documentation, perhaps also showing it as a warning near the instructions for switching from HyperV to VirtualBox?

**Comment by ibehren1** [comment]
Is the issue with bridged networking because the snap has no interfaces defined?

I have set the driver to libvirt and multipass spins up the instance find on the libvirt side, the instance gets an IP from my network dhcp server and is good but multipass times out and never gets the "metadata".  As a result it only has the ability to stop/start the VM but takes forever to do so b/c it cannot connect to it.

I found the ssh key buried in the /var/snap/... dir and can get on the instance.  All good there.  Seems like it should be simple enough to allow multipass to talk to outside network.

Without bridged networking, the use case for multipass is pretty limited.  If bridged networking can be enabled, it is a fabulous interface to libvirt which adds a ton of use cases.  Love the simplicity of spinning of instances and specifying base cpu/mem/disk and getting a working base OS in seconds.

**Comment by Saviq** [comment]
The issue with bridged networking is that Multipass (nor the hypervisor) are in control of the network any more. So long as we rely on networking to the instance, we need to know the IP of the instance. We're taking that from the hypervisors' DHCP servers today - when bridging, we don't have that source.

We could scrape the console output, but that proves unreliable.

In the future we want to switch to interacting with the instance over [vsock](http://man7.org/linux/man-pages/man7/vsock.7.html) (or platform equivalent), which would make this feature quite a bit simpler.

**Comment by ssx** [comment]
Is there any ETA on this? Multipass could solve a bunch of problems for one of my clients but it requires bridged networking (and then DHCP from the host network).

**Comment by JasLin** [comment]
i means it should create Virtual Ethernet Card Adapter for every instance,  and obtain ip from LAN DHCP

that will cause something inconvenient,  it means ip of every instance is associate with the local network(WIFI), if we move to another network, instance's ip will change. if you use this ip between you instance, than you application will throw some errors like 'Time out'. 

so we should keep use internal network ip (which use between instances) and expose ip got from LAN, they have one-2-one relations.

**Comment by hemna** [comment]
would also like to have bridged networking so my vm can ping other systems in my local network and vice versa.   Have to stick with vagrant vms until then.

**Comment by kush-daga** [comment]
https://jon.sprig.gs/blog/post/1574
This is a blog that might be useful in this :)

**Comment by foobarbecue** [comment]
I installed multipass because I read that it did networking so thought it would do this... without the ability to listen on a physical interface, multipass is useless to me.

**Comment by sylvandb** [comment]
Multipass absolutely needs bridged networking.

Instead of bridging the existing virtual nic and causing management complexity, simply add a second nic.

Ideally this would be an option on the multipass command line such that I could specify nothing for the existing behavior, or a number of additional network interfaces. I could add the additional nic(s) to host-side bridge(s) myself if/as needed.

**Comment by Saviq** [comment]
Hi @sylvandb that's exactly what we'll be working on, soon :)

**Comment by AriESQ** [comment]
For windows, I have "bridged networking" with Hyper-V working.

https://discourse.ubuntu.com/t/solution-multipass-not-reachable-from-outside-windows-10-networking-host/16392

**Comment by a1git** [comment]
Hi, 

Checking if there is a date/milestone when the bridge support will be released ?

**Comment by Saviq** [comment]
Hi @a1git we're actively working on it now, it should land in our next release in a month or so.

**Comment by foobarbecue** [comment]
Any update on this?

**Comment by Saviq** [comment]
> Is there a workaround tutorial when using an Ubuntu host as well?

If you use the lxd or libvirt backends (`sudo multipass set local.driver=…`), you can use `lxc` or `virsh`, respectively, to configure any additional network interfaces.

> Any update on this?

We're working on this, it's coming soon :)

**Comment by foobarbecue** [comment]
How about now, any update?

**Comment by Saviq** [comment]
> How about now, any update?

You will find a couple PRs towards this in [our list](https://github.com/canonical/multipass/pulls). We plan to release around the end of the month.

**Comment by foobarbecue** [comment]
End of which month?

**Comment by Matisds** [comment]
This feature would be very welcome now!

**Comment by colegatron** [comment]
Nov 16. is it released? Multipass without bridging is like Coke but without bubbles.

**Comment by ikiK-CRO** [comment]
Just to give + on this feature and join those who need this, in my case badly. Otherwise multipass is best thing ever, or will be with this option 👍 

Thanks for work invested in this.

**Comment by ricab** [comment]
A few details are still missing from those packages (e.g. early network validation, release of unused mac addresses). They are coming soon, but we have a bunch of stacked PRs that we want to merge first.

**Comment by ibehren1** [comment]
```
launch failed: Could not start VM: VBoxManage: error: The virtual machine 'impeccable-pika' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
```

I suspect this is a local VirtualBox error as occurs with/without the --network option, however updating the install of VirtualBox did not resolve.  Curious if this is a known issue or a suggested resolution is available.

MacOS BigSur and VirtualBox Version 6.1.16 r140961

**Comment by Saviq** [comment]
Hi @ibehren1, this indeed doesn't seem related to this feature, or necessarily to Multipass even. If you launch with `-vvv`, can you see more interesting information? Or in the `multipassd.log` (see [our docs on where to find it](https://multipass.run/docs/accessing-logs#macos))?

**Comment by sam-mlcoder** [comment]
Hi team, I am able to install the new multipass and used the multipass launch --network command to launch the ubuntu instance, now I can access the webserver from other devices in the network.
**Note**: Antivirus was blocking as the fix was not signed I think, I have disabled and able to install and launch.
Thanks for the fix 👍

**Comment by SlyCooperking** [comment]
Passing the PS >multipass list-networks doesn't seem to provide a ID value needed for the >multipass launch --network <spec> argument. I guessed the argument accepts a string '<instance name>' and it seems to add both my Hyper-V's default switch and the external one I made.

**Comment by foobarbecue** [comment]
Just tried it on Windows and it works great! Thanks so much!!!

**Comment by jconlon** [comment]
Working for me on MacOS Big Sur!

**Comment by a1git** [comment]
I am on ubuntu 20 

multipass  1.5.0
multipassd 1.5.0

multipass launch --network 
Unknown option 'network'.

**Comment by Saviq** [comment]
@a1git only VirtualBox and Hyper-V are implemented so far. We're working on the other platforms now.

**Comment by takogata** [comment]
@ricab Is the preliminary version (for Windows) still available somewhere? I get a _403 Access denied_  [using the download links.](https://github.com/canonical/multipass/issues/118#issuecomment-734426114)

**Comment by Saviq** [comment]
> @ricab Is the preliminary version (for Windows) still available somewhere? I get a _403 Access denied_ [using the download links.](https://github.com/canonical/multipass/issues/118#issuecomment-734426114)

Now available on the 1.6.0 RC tag:

https://github.com/canonical/multipass/releases/tag/v1.6.0-rc

**Comment by yorch** [comment]
@Saviq is there any Github issue tracking the progress? I would love to use bridged networking on my Ubuntu box running multipass. Thanks!

**Comment by SlyCooperking** [comment]
> @Saviq is there any Github issue tracking the progress? I would love to use bridged networking on my Ubuntu box running multipass. Thanks!

I think they had gotten it working for the most part. I can now host servers with my multi pass instances and ping them from a client.

**Comment by yorch** [comment]
@SlyCooperking how did you configure it them? I'm getting: `networks failed: The networks feature is not implemented on this backend.` when trying to run `multipass networks`

**Comment by SlyCooperking** [comment]
@yorch  Perhaps someone else might be able to jump in, I don't remember the error I received before making changes, but Perhaps similar changes will help you.

You will need to create a vEthernet (External Switch) appear in Control Panel\Network and Internet\Network Connections

You may need to create a network bridge between your wifi adapter connection and your vEthernet (External Switch) both should be in the above control panel location. 

This May get you started on creating the virtual switch and bridge, which you will need to do within Hyper-V https://docs.microsoft.com/en-us/windows-server/virtualization/hyper-v/get-started/create-a-virtual-switch-for-hyper-v-virtual-machines

AS for the network bridge This may be of help. https://www.windowscentral.com/how-set-and-manage-network-bridge-connection-windows-10

Hope this helps.

**Comment by yorch** [comment]
@SlyCooperking thanks, unfortunately, I'm using Ubuntu as my host.

**Comment by Saviq** [comment]
> @SlyCooperking thanks, unfortunately, I'm using Ubuntu as my host.

Hi @yorch, the feature is available on Linux, too, using the LXD backend. Use `sudo multipass set local.driver=lxd` to switch to it, then networks will work. You will need to create the bridge yourself while we're working on making this automatic where possible.

**Comment by dennistanaka** [comment]
Just passing by to say thank you, this feature is great. I even had stopped trying multipass before `1.6` due to the lack of bridge support, but I tested `1.6.1` on Windows 10 + Hyper-V and could access the VM with no problems from another machine in the network. I usually don't use this Windows desktop for development and I wanted to put its resources for use while on and not playing games, and it's been great to use Multipass to run VMs on it. Thanks!

**Comment by ikiK-CRO** [comment]
Does  multipass-1.6.1+mac-Darwin.pkg (that is RC relase?) has support for bridged network without suing VirtualBox? I cant use VirtualBox on some machines as there conflict with some FUSE  (sshfs) features that I use. If not will there be some native OSX solution?

**Comment by rgigger** [comment]
> Working for me on MacOS Big Sur!

Was this with virtual box?

**Comment by Saviq** [comment]
@ikiK-CRO @rgigger on macOS only VirtualBox is supported now. We'll be working on integrating with the new virtualization API in Big Sur soon. It will fall together with #1857.

We forgot to close this, too.

**Comment by underrun** [comment]
@Saviq is there an issue tracking bridged networking support for macos with native apis / non-virtualbox separate to the ARM related ticket? if it's all the same work then maybe the title could reflect that? if there's a bridging specific ticket for other hypervisors on macos could you link it here?

**Comment by Saviq** [comment]
@underrun no separate ticket, it will come along with the new API support. I've changed the title there to "Apple M1 / Virtualization framework support" so that it reflects more what needs to happen. Won't call out bridging specifically, we'd have to list much more that way.

**Comment by maximehyh** [comment]
Hello, 

Would it be possible to have a detailed example on how to set this up?  I am currently running multipass on `Windows` and I am having trouble exposing my service on the network.

So far I have been trying the following (I am using Hyper-V): 

List of available network interfaces (I wonder if the ones of interest are not missing?)
```powershell
PS C:\Windows\system32> multipass networks
Name            Type    Description
Default Switch  switch  Virtual Switch with internal networking
WSL             switch  Virtual Switch with internal networking

PS C:\Windows\system32> multipass set local.bridged-network="Default Switch"
PS C:\Windows\system32> multipass launch --bridged
PS C:\Windows\system32> multipass list
Name                    State             IPv4             Image
compatible-chicken      Running           172.20.227.149   Ubuntu 20.04 LTS
                                          172.20.237.96
```

Making sure I can access the service from the host: 
```powershell
PS C:\Windows\system32> curl http://172.20.227.149:32218/ -UseBasicParsing
StatusCode        : 200
StatusDescription : OK
Content           : Hello, world!
                    Version: 1.0.0
                    Hostname: hello-world-57fbf88c7-xx6p5

RawContent        : HTTP/1.1 200 OK
                    Content-Length: 67
                    Content-Type: text/plain; charset=utf-8
                    Date: Wed, 30 Mar 2022 03:05:01 GMT

                    Hello, world!
                    Version: 1.0.0
                    Hostname: hello-world-57fbf88c7-xx6p5

Forms             :
Headers           : {[Content-Length, 67], [Content-Type, text/plain; charset=utf-8], [Date, Wed, 30 Mar 2022 03:05:01 GMT]}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        :
RawContentLength  : 67
```

FYI the service is running in `microk8s` but I do not think this is really relevant as I am already able to access the service from the host.

Thanks

**Comment by NobShen** [comment]
Using multipass 1.9.2, I'm able to create VM's with ipv4 addr from my local network by bridging to eth0 .  However, doing so would remove ipv4 addr from my host PC.  Now I can't ssh into the host PC from another PC but I can ssh to the VM fine.  Is this a bug?

**Comment by Saviq** [comment]
Hi @NobShen, it doesn't _remove_ it, but indeed it changes it - it's the bridge that gets the IP (and it has a different MAC address), not the physical interface.

**Comment by daviewales** [comment]
If you've ended up here because you want to connect to multipass from WSL, I don't think you need the bridged networking. You need to enable forwarding on the Windows side. (See [comment on WSL issue](https://github.com/microsoft/WSL/issues/4288#issuecomment-778790363))

From an admin PowerShell:

``` ps1
Set-NetIPInterface -ifAlias "vEthernet (WSL)" -Forwarding Enabled
Set-NetIPInterface -ifAlias "vEthernet (Default Switch)" -Forwarding Enabled
```

Now you can connect to multipass from WSL.
