### ISSUE TITLE
Any language buildings/sdks available for multipass?

### ISSUE THREAD

**Issue by afritzler** [canonical/multipass#1254]
Are there any sdks available for multipass? Go language bindings would be great to spin up some cool automation tooling around multipass.

**Comment by Saviq** [comment]
Hi @afritzler at the moment the only entry point is the `multipass` CLI, we're keeping it stable for that purpose.

We use [gRPC](https://grpc.io/) for communication between the clients and daemon, but we don't yet claim [the protocol](https://github.com/canonical/multipass/blob/v1.0.0/src/rpc/multipass.proto) stable, so that may break at some point (but we won't be breaking it without good reason).

Hope this helps?

**Comment by afritzler** [comment]
Thanks a lot for the quick response. And yes, the proto file helps! Closing.
