### ISSUE TITLE
Unaligned ttyname/ioctl errors

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#1310]
Noticed some unaligned ttyname/ioctl errors when running snapcraft with edge-channel multipass (1.1.0-dev.47+g31ad44c). 

```console
ricab@ricab-xps13:~/mydev/test-snap/snap $ snap refresh --edge multipass
multipass (edge) 1.1.0-dev.47+g31ad44c from Canonical✓ refreshed
ricab@ricab-xps13:~/mydev/test-snap/snap $ snapcraft
Launching a VM.
Launched: snapcraft-test-snap
mesg: ttyname failed: Inappropriate ioctl for device
                                                    mesg: ttyname failed: Inappropriate ioctl for device
   mesg: ttyname failed: Inappropriate ioctl for device
                                                       error: no changes of type "auto-refresh" found
2020-01-16T18:28:40Z INFO Waiting for restart...
snapd 2.42.5 from Canonical✓ installed
[...]
```

Snapcraft otherwise completes well. These messages don't appear with stable (1.0.2). Could this be related to libssh now polling for stderr? 

I do not observe this when using multipass directly. This may well be under snapcraft scope, but opening an issue anyway so it can be discussed and maybe routed.

**Comment by townsend2010** [comment]
@ricab,

Yes, this is due to both the `libssh` patch to fix reading `stderr` and now handling redirected `stdio` properly.  It's basically the result of `snapcraft` using the Python `subprocess.check_output` when using `sudo -i` inside the instance.  An example would be:
```
python -c "import subprocess;subprocess.check_output(['bin/multipass', 'exec', 'foo', '--', 'sudo', '-i', 'echo', 'hi'])"
```

As far as the unaligned output, yeah, I saw that and it needs to be fixed but it's only a visual thing and doesn't affect functionality.  BTW, I think the fix needs to happen in `libssh`.

**Comment by ricab** [comment]
Hi @townsend2010 , I see. So IIUC the issue is them using a login shell, which ends up executing `mesg`, which doesn't get a tty but needs one, correct? Not much we can do on our side I suppose.

As to the unaligned output, is that something you have seen in other cases too?
