### ISSUE TITLE
multipassd crash

### ISSUE THREAD

**Issue by anonymouse64** [canonical/multipass#1315]
After one of my multipass VM's went to restart (it was a Ubuntu Core 16 VM if that's relevant), multipassd crashed: https://pastebin.ubuntu.com/p/Grm5WNznRb/

There were no updates and no `snap restart` commands, etc.

**Comment by townsend2010** [comment]
Hey @anonymouse64,

Thanks for posting this!

Looking through the logs, it looks like a `start` was issued on the instance while it was in the process of `restarting`.  Do you happen to remember if you issued a `multipass start` on the core16 instance?  Although I do see a bug in our state handling in this case, I'd like to confirm if this is indeed what happened to you.  Otherwise, I really see no other way how a `start` was done on the instance here.  

At any rate, I'll work on a fix to protect against the behavior I see here.

**Comment by anonymouse64** [comment]
@townsend2010 I don't recall which multipass command I issued, it's likely I ran `multipass shell` a minute or two after the machine stopped to reboot itself.

**Comment by townsend2010** [comment]
@anonymouse64, ah, yes, `shell` would probably do it to.  I think we are not accounting for the `restarting` state very well which is leading to this.  Thanks and I'll work on a fix!
