### ISSUE TITLE
[health] bad expericence when nesting impossible

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1342]
We seem to fail to detect being in a VM in the first place, and we're failing ungracefully:

https://bugs.launchpad.net/snapcraft/+bug/1859424

**Comment by townsend2010** [comment]
So, I think it's relatively trivial for Multipass to detect it's running in a virtualized *Linux* guest using something like `virt-what`.  However, I've not seen anything that can probe a guest to know whether the hypervisor supports nesting or if nesting is enabled.

As for Multipass running on another type of virtualized guest such as Windows, I think that is not so trivial.  We'll need to do more research to determine if it's possible to detect.

In my opinion, we should do this:
 - For "production" versions of Multipass, we should not allow running in a virtualized environment.
 - Make every effort to detect at the installer level to determine if Multipass is being installed in a virtualized environment and fail the install if so.
- For CI, we can add some way to force the install since we will have a stable, nested environment that we control.

**Comment by Saviq** [comment]
Thanks @townsend2010, that's quite meh :/

This is going into a `multipass set …nesting=true` direction, you'd think that this kind of thing would be worth knowing/exposing…

**Comment by Saviq** [comment]
_Actually_:
```bash
$ uname -r
5.4.0-12-generic
$ multipass exec primary sudo kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used
$ multipass exec primary -- snap run multipass launch snapcraft:core18 --mem 256M
Launched: sterling-earwig
$ multipass stop
$ rmmod kvm_intel
$ modprobe kvm_intel nested=0
$ multipass start
$ multipass exec primary sudo kvm-ok
INFO: Your CPU does not support KVM extensions
KVM acceleration can NOT be used
```

So at least on newer kernels, nesting is enabled by default. And if you explicitly disable it, Multipass notices fine.

The original problem on Launchpad seems to be memory - a Multipass instance by default has 1GB memory… so launching a new instance without a `--mem` argument fails simply because there's not enough free memory.

**Comment by Saviq** [comment]
Since fixing #1312, however, the error reported is much better than before:
```bash
$ multipass exec primary -- snap run multipass launch snapcraft:core18           
launch failed: The following errors occurred:                                   
qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory
evolved-peacock: shutdown called while starting
```
