### ISSUE TITLE
Allow additional disks

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#135]
Allow the ability to add secondary disks to the guest.

For example, `uvtool` can do this at launch time with `--ephemeral-disk=5`
The value provided is the size in GB that you want to attach.

**Comment by townsend2010** [comment]
@smoser, libvirt is now supported[0], so after creating a Multipass instance, you can use `multipass.virsh` to add a disk.  If you need an extra disk at launch time, then that is not currently supported and is, at the moment, a fairly low priority item.

[0] `$ sudo snap set multipass driver=LIBVIRT`

**Comment by smoser** [comment]
As I'm sure is true with others, when someone tells me I can just use libvirt, I have bad memories of xml and frustrations.  So... in order to show how you can actually do this, I'll doc that here.

I'm doing this on version `2018.4.2-22-g6bc5c82` (per multipass --version).

## Set multipass to use the libvirt driver
You'll first have to change multipath to use the libvirt driver.  To do that:

    $ sudo snap set multipass driver=LIBVIRT

If you  use a proxy it might be useful for you to set http proxy for multipass download also:

    $ sudo snap set multipass proxy.http=http://10.10.10.10:3128/
    
## create a domain
    $ dom=smb1
    $ multipass launch daily:bionic --name=$dom

You can watch it boot on the console like:

    $ multipass.virsh console $dom


## creating a storage pool for volumes.
Now, create a storage pool.  The path 'pool_path' has to already exist in in the host's filesystem.  Ie, `/var/lib/libvirt/images`, not `/snap/multipass/current/var/lib/images`.

    $ pool="mypool"
    $ pool_path="/var/lib/libvirt/images"
    $ multipass.virsh pool-define-as $pool --type=dir "--target=$pool_path"
    $ multipass.virsh pool-start $pool
    
## create a volume
    $ vol="myvol"
    $ multipass.virsh vol-create-as --pool=$pool --name=$vol \
        --capacity=1GB --format=qcow2
        
At this point, in the hosts' filesystem you'll have a file in $pool_path:

    $ sudo qemu-img info /var/lib/libvirt/images/myvol
    image: /var/lib/libvirt/images/myvol
    file format: qcow2
    virtual size: 954M (1000000512 bytes)
    disk size: 196K
    cluster_size: 65536
    Format specific information:
        compat: 0.10
        refcount bits: 16

## attach it to a domain.
    $ devname="vde"
    $ multipass.virsh attach-device --live $dom /dev/stdin <<EOF
    <disk type='volume' device='disk'>
      <driver name='qemu' type='qcow2'/> 
      <source pool='$pool' volume='$vol'/>
      <serial>myserial</serial>
      <target dev='$devname'/>
    </disk>
    EOF

## inside the volume, you'll have the disk.

    $ multipass exec smb1 -- sudo udevadm info /dev/vdc
    P: /devices/pci0000:00/0000:00:07.0/virtio4/block/vdc
    N: vdc
    S: disk/by-id/virtio-myserial
    S: disk/by-path/pci-0000:00:07.0
    S: disk/by-path/virtio-pci-0000:00:07.0
    E: DEVLINKS=/dev/disk/by-path/pci-0000:00:07.0 /dev/disk/by-id/virtio-myserial /dev/disk/by-path/virtio-pci-0000:00:07.0
    E: DEVNAME=/dev/vdc
    E: DEVPATH=/devices/pci0000:00/0000:00:07.0/virtio4/block/vdc
    E: DEVTYPE=disk
    E: ID_PATH=pci-0000:00:07.0
    E: ID_PATH_TAG=pci-0000_00_07_0
    E: ID_SERIAL=myserial
    E: MAJOR=252
    E: MINOR=32
    E: SUBSYSTEM=block
    E: TAGS=:systemd:
    E: USEC_INITIALIZED=237586586


## tearing things down
All done playing, heres how to delete all those things.

    $ multipass.virsh detach-disk --live $dom $devname
    $ multipass.virsh vol-delete $vol $pool
    $ multipass.virsh pool-destroy $pool
    $ multipass.virsh pool-undefine $pool
    $ multipass destroy $dom
    $ multipass purge

**Comment by Saviq** [comment]
I'll close this on account of this being an advanced usecase, achievable with the `libvirt` backend today.
