### ISSUE TITLE
[transfer] not creating target directory

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1434]
```
$ multipass transfer file primary:missing/file
transfer failed: [sftp push] open failed: 'SFTP server: No such file'
$ multipass exec primary mkdir missing
$ multipass transfer file primary:missing/file
$ # worked
```

_Originally posted by @jasonmccallister in https://github.com/canonical/multipass/issues/1165#issuecomment-600307143_

**Comment by townsend2010** [comment]
We need to think about the design for this.  I see two viable options on how this could be handled:
- Any missing directories are just created.
- An option like `lxc file push` uses, ie, `-p, --create-dirs`.  If there are missing directories and this option is not given, then it's an error with appropriate message.

Any comments?

**Comment by Saviq** [comment]
I'd go for:
> Any missing directories are just created.

**Comment by ricab** [comment]
I am on the fence. Unnecessary typing is best avoided, but the advantage I see in `-p` is detecting *some* mistakes early. For instance, consider:

1. `multipass transfer $HOME/file primary:$HOME/file`
2. `multipass transfer file ./Douments/file`

On 1. we might actually create `/home/<outside_user>/file`, depending on how we handle permissions. On 2. the typo would result in a new dir. On both cases, requiring `-p` would expose the error. But this would of course not help with typos when dir creation was intended.

However, that is exactly how `mount` behaves, so it may be better to go for consistency across commands. The situation is actually worse there, because the target dir can be implicit: `multipass mount ~/file <instance>` does create `/home/<outside_user>/file` today.

**Comment by townsend2010** [comment]
As far as permissions, we are using the `sftp` protocol for this, so permissions are set by the `ssh_server` in the instance.

**Comment by townsend2010** [comment]
And to add, since we are using the security of ssh here, that is the reason for #1433 for which I'm not convinced is a problem or at least is not something multipass should deal with.

**Comment by ricab** [comment]
Yeah, I saw that and was unsure how that part will play out.
