### ISSUE TITLE
Bash completion does not include short versions or aliases

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#153]
The following are examples of what breaks autocompletion:
`multipass delete -p<Tab>`
`multipass sh <Tab>`

Both are valid multipass commands, but don't include full versions of the options / commands, which results in interrupted completion.

**Comment by townsend2010** [comment]
Ok, for sure need to include command aliases to the list of commands.

As far as short versions, there seems to be an unwritten "good practice" to use the long option only and only fallback to a short option if no long option is available.  From what I've read, the reason is that the long option is more informative to use discovering what the options are.  I'm not sure how you feel about this and it's fairly trivial to add short options as well, although it will clutter up option discovery.

For example, `launch` will look something like:
`$ multipass launch -<Tab>`
`-c            --cloud-init  --cpus        -d            --disk        -h            --help        -m            --mem         -n            --name        -v            --verbose`

**Comment by townsend2010** [comment]
Also, for command aliases, we should any all aliases, such as the old `connect` which is now an alias?

**Comment by albaguirre** [comment]
For aliases, I guess it should be consistent with the help output. If we list them on the help (no aliases are currently listed there) then they should be undiscoverable.

For short options - I think less clutter makes sense so I vote for short options to be undiscoverable. IIUC, the only side-effect of this is that the user has to manually insert a space after something like delete -p <TAB> right?
