### ISSUE TITLE
multipass info doesn't show disk location

### ISSUE THREAD

**Issue by parrotcar00** [canonical/multipass#1551]
How does one find out the location for the virtual HDD that multipass uses for any vm?

I thought multipass info $VM_NAME would show the location of the virtual disk file?

**Comment by Saviq** [comment]
Hi @parrotcar00 the location of the file is (at the moment) an internal detail. There's no way to move it, and modifying it is unsupported.

May I ask what's your use case?

**Comment by parrotcar00** [comment]
I wanted to be able to make sure that in case of something bad happening to my vm, I can get my data out. So I was trying to figure out where the disk files are located that I could copy?

Another possible way might be for me to take daily snapshots of the vm, does multipass support this?
I'm just trying to figure out how do can I use multipass when I need to backup my vm data periodically?

**Comment by parrotcar00** [comment]
Also, I wanted to add that I'd always be using this on an Ubuntu host running Linux guests, so I wouldn't be affected by by other platform incompatibilities.

**Comment by Saviq** [comment]
@parrotcar00 it's recommended that you `multipass mount` important data into your VM, rather than storing it inside, this way you can easily replace an instance with another.

Snapshotting is not currently supported (#208), but since Multipass is a snap, you can `snap save` its data. All data is stored in `/var/snap/multipass/`.

**Comment by Saviq** [comment]
I'm gonna close this as we'd rather not expose this detail, at least not without introducing support for configuring storage.

**Comment by paulstelian97** [comment]
Because of this I cannot resize my Multipass disk on macOS, and since recreating would take me a full week of downtime I'll ditch it. Completely disappointed because of the default of 5GB which is COMPLETELY inadequate for everything. And for my usecase (running a specific version of the Haskell platform since I cannot find the exact configuration on my macOS host) I cannot use a shared folder either.

**Comment by Saviq** [comment]
@paulstelian97 the issue relevant for resizing has manual steps to resize:

https://github.com/canonical/multipass/issues/62#issuecomment-729650082

**Comment by paulstelian97** [comment]
> @paulstelian97 the issue relevant for resizing has manual steps to resize:
> 
> [#62 (comment)](https://github.com/canonical/multipass/issues/62#issuecomment-729650082)

Thanks, you kinda came in too late to save me. I have tried some things which ended up corrupting my Multipass instance and forced me to recreate it. Eh, after like one or two hours of being frustrated I just recreated it, thankfully I didn't _actually_ have much important data in it. Had to increase memory as well (1GB wasn't enough) anyway.

**Comment by Saviq** [comment]
> Thanks, you kinda came in too late to save me.

Heh, trying, it's Sunday here ;)

Glad you got it working, we do have to err on the conservative side for default resources. But yes we'll definitely allow resizing / changing memory / CPU and other properties of instances.

**Comment by jimthedj65** [comment]
> > Thanks, you kinda came in too late to save me.
> 
> Heh, trying, it's Sunday here ;)
> 
> Glad you got it working, we do have to err on the conservative side for default resources. But yes we'll definitely allow resizing / changing memory / CPU and other properties of instances.

Any idea when the ability to resize a disk will be available?
