### ISSUE TITLE
SSL corruption when using `-vvv`

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#1570]
**Describe the bug**
Some multipass commands fail when verbosity is debug or above, reporting some corruption in SSL transport:

```
/E0529 18:15:10.656399660   59826 ssl_transport_security.cc:483] Corruption detected.
E0529 18:15:10.656415748   59826 ssl_transport_security.cc:459] error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
E0529 18:15:10.656422831   59826 ssl_transport_security.cc:459] error:1000008b:SSL routines:OPENSSL_internal:DECRYPTION_FAILED_OR_BAD_RECORD_MAC
E0529 18:15:10.656428523   59826 secure_endpoint.cc:208]     Decryption error: TSI_DATA_CORRUPTED
E0529 18:15:10.656447885   59826 ssl_transport_security.cc:510] SSL_write failed with error SSL_ERRORmount failed: Stream removed
```

I observed this with `start` and `shell` when using the `qemu` backend. It appears to be triggered by some message that is only produced in these cases. I don't get the same with `launch` nor with `libvirt`, nor with `-vv` (but I do with `-vvvv`). 

(Hunch: some overflow caused by big msgs, like qemu cmd line or AppArmour??)

**To Reproduce**

1. `multipass set local.driver=qemu`
1. `multipass launch -n foo`
1. `multipass stop foo`
1. `multipass start foo -vvv`

Example run on the CLI: 
```
$ multipass start outspoken-teal -vvv
Starting outspoken-teal -[2020-06-01T18:04:37.005] [debug] [outspoken-teal] process working dir '/snap/multipass/2126/qemu'
  [2020-06-01T18:04:37.005] [info] [outspoken-teal] process program 'qemu-system-x86_64'
 [2020-06-01T18:04:37.005] [info] [outspoken-teal] process arguments '--enable-kvm, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/snap/multipass/common/data/multipassd/vault/instances/outspoken-teal/ubuntu-18.04-server-cloudimg-amd64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 1, -m, 1024M, -device, virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:cd:73:b1, -netdev, tap,id=hostnet0,ifname=tap-10cab1594dd,script=no,downscript=no, -qmp, stdio, -cpu, host, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/snap/multipass/common/data/multipassd/vault/instances/outspoken-teal/cloud-init-config.iso'
 /[2020-06-01T18:04:37.025] [warning] [qemu-system-x86_64] qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]

 /[2020-06-01T18:04:37.071] [debug] [daemon] Applying AppArmor policy: multipass.outspoken-teal.qemu-system-x86_64
 /E0601 18:04:37.072766619   36242 ssl_transport_security.cc:483] Corruption detected.
E0601 18:04:37.072787070   36242 ssl_transport_security.cc:459] error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
E0601 18:04:37.072793314   36242 ssl_transport_security.cc:459] error:1000008b:SSL routines:OPENSSL_internal:DECRYPTION_FAILED_OR_BAD_RECORD_MAC
E0601 18:04:37.072797851   36242 secure_endpoint.cc:208]     Decryption error: TSI_DATA_CORRUPTED
E0601 18:04:37.072813385   36242 ssl_transport_security.cc:510] SSL_write failed with error SSL_ERRORstart failed: Stream removed
```
Note: the odd slashes and spaces at BOL appear to be produced by the spinner.)

**Expected behavior**
Command would complete with no errors.

**Logs**

Nothing special on the daemon side

```
jun 01 17:57:13 ricab-xps13 multipassd[32061]: process working dir '/snap/multipass/2126/qemu'
jun 01 17:57:13 ricab-xps13 multipassd[32061]: process program 'qemu-system-x86_64'
jun 01 17:57:13 ricab-xps13 multipassd[32061]: process arguments '--enable-kvm, -device, virtio-scsi-pci,id=scsi0, -drive, file=/var/snap/multipass/common/data/multipassd/vault/instances/outspoken-teal/ubuntu-18.04-server-cloudimg-amd64.img,if=none,format=qcow2,discard=unmap,id=hda, -device, scsi-hd,drive=hda,bus=scsi0.0, -smp, 1, -m, 1024M, -device, virtio-net-pci,netdev=hostnet0,id=net0,mac=52:54:00:cd:73:b1, -netdev, tap,id=hostnet0,ifname=tap-10cab1594dd,script=no,downscript=no, -qmp, stdio, -cpu, host, -chardev, null,id=char0, -serial, chardev:char0, -nographic, -cdrom, /var/snap/multipass/common/data/multipassd/vault/instances/outspoken-teal/cloud-init-config.iso'
jun 01 17:57:13 ricab-xps13 multipassd[32061]: qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
jun 01 17:57:13 ricab-xps13 multipassd[35713]: Applying AppArmor policy: multipass.outspoken-teal.qemu-system-x86_64
jun 01 17:57:13 ricab-xps13 multipassd[32061]: process started
jun 01 17:57:13 ricab-xps13 multipassd[32061]: QMP: {"QMP": {"version": {"qemu": {"micro": 1, "minor": 11, "major": 2}, "package": "(Debian 1:2.11+dfsg-1ubuntu7.26)"}, "capabilities": []}}
jun 01 17:57:13 ricab-xps13 multipassd[32061]: QMP: {"return": {}}
```

**Additional info**
 - OS: ubuntu 20.04
- `multipass version`
multipass  1.3.0-dev.63+g6f7a41e5
multipassd 1.3.0-dev.63+g6f7a41e5
(edge snap)
- `snap info multipass | grep installed`
installed:          1.3.0-dev.63+g6f7a41e5            (2126) 214MB -

**Comment by townsend2010** [comment]
As I was working on #2055, I of course ran into this issue during `launch`.  I have narrowed it down to https://github.com/canonical/multipass/blob/d5ae628401987b18bb12e4b1982eff9d62422d24/src/platform/backends/shared/linux/apparmor.cpp#L128, but at this time, it makes no sense why this line causes the error.

If I remove the line, the client logging works and many messages will be printed in the client with no issues.  If I even change the line to something like:
```
mpl::log(mpl::Level::debug, "daemon", "Hello!");
```

the same gRPC SSL error occurs.  I'm still digging into the root cause, but very strange nonetheless.

**Comment by townsend2010** [comment]
After some more digging, I found that the log message is being called in an override of `QProcess::setupChildProcess()` which according to https://doc.qt.io/qt-5/qprocess.html#setupChildProcess is run in the child process's context after `fork()` but before `execv()`.

At this point, there is something going on with the SSL connection wrt to a new pid yet still using the same SSL connection via gRPC.  I'm not sure if this is a bug in OpenSSL, a needed configuration change in OpenSSL, or an issue in gRPC, but instead of spending any more time trying to figure that out, I will just put a workaround in place that removes that logging call and move it to a different place that gets called in the original process context.
