### ISSUE TITLE
[lxd] shows "Retrieving image: 100%" before going back to 0%

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1612]
**Describe the bug**
When launching an instance with LXD, a spurious "Retrieving image: 100%" is shown before the count starts.

**To Reproduce**
How, and what happened?
1. `multipass set local.driver=lxd`
1. `multipass launch`

**Expected behavior**
Image download reported correctly.

**Additional info**
 - OS: Ubuntu 20.04
- `multipass version`: 1.3.1
- `multipass info --all`: N/A

**Comment by townsend2010** [comment]
Yep, this is a known issue as highlighted in #1586 (third from the bottom as of this writing), but it's still good to break it out as a separate bug for when the time comes to fix it.

**Comment by townsend2010** [comment]
I'll also mention that the issue seems from LXD does 2 separate downloads when fetching an image.  The first download is the "metadata" which is where the first 100% comes from and then the second download is the main image which is the correct percent download.

We just need to figure out how best to display this in the UI. Do we ignore the metadata download? Do we do what the `lxc` client does and display both parts as separate download resources?

**Comment by matthewpaulthomas** [comment]
If this was a graphical progress bar, the solution would be to estimate the relative sizes of the two downloads ahead of time, and allocate a corresponding fraction of the progress bar to each. But it wouldn’t really be honest to do that when printing a precise percentage number.

Instead, how about something like
`Downloading: metadata…`
which becomes
`Downloading: image… 0%`

**Comment by townsend2010** [comment]
I'm a little concerned that having a `metadata` part and then the `image` part deviates from what all other backend driver types present, ie, just `Downloading: 0%`.  Should we switch all other types to show `Downloading: image… 0%` as well for a (mostly) consistent UI experience?

**Comment by matthewpaulthomas** [comment]
Sure, they should be consistent on whether they use “Retrieving” or “Downloading”, and whether they use an ellipsis (I don’t have a strong preference on either detail).

They shouldn’t all specify “image”, though, because the point of including it is to make a distinction between “this is the percentage for all of the task” and “this is the percentage for part of the task”.

**Comment by Saviq** [comment]
I think the solution here is to ignore the metadata download. It's only hundreds of bytes, it doesn't play at all into the overall percentage.
