### ISSUE TITLE
Mount poor i/o performance

### ISSUE THREAD

**Issue by clubh** [canonical/multipass#1759]
Not sure if this is a Multipass issue, probably not, but would like to know if anyone else has the same issue. I've seen poor mount i/o performance described elsewhere, but have so far not found a solution.

Running an i/o read test within the instance on a mounted directory, is substantially slower than running the same test on the instance file system and on the host that contains the mounted directory:

This is the read test done from 3 different starting points:

`$ iozone -i 1 -r 64k -s 2G -f iozone.tmp`

- Within instance to mounted directory: **37,558 KB/s**
- Within the instance filesystem: **966,404 KB/s**
- On host filesystem (mounted directory): **3,103,163 KB/s**

Is there a way to improve the i/o performance on the mount? 

OS: macOS Catalina
Multipass: 1.4.0

**Comment by oleg-andreyev** [comment]
I've been struggling with same question and issue (but on Windows), when I execute "npm ci" (removing node_modules/ and installing everything from lock file) sshfs is hanging either on VM side or Windows. As a solution I've decided not to use sshfs and https://github.com/bcpierce00/unison to sync files between host and vm and the only issue is that I have a "slight delay" when doing initial sync and when doing massive update (same npm ci command)

**Comment by arobertn** [comment]
I too am experiencing poor performance on shared mounts with multipass on MacOS and will share a bit of somewhat real world data. Specifically I tested du (traversal), tar and untar (read and write), and rm for a 1.8GB directory tree with 6K directories and 13K files. The tar/untar used gz compression since typical use also includes a mix of CPU and disk load. I compared Multipass for internal and shared mounts with Parallels with the same. Since Parallels has an option to use Apple's native hypervisor instead of its own, I tried this also to get a more direct comparison with multipass.

I will give the summary here, and the results are in an [attached file](https://github.com/canonical/multipass/files/6254890/disk_bench.txt).

- Parallels (either hypervisor) is about 20% faster than multipass on internal mounts and 5x faster on reads, 10x faster on writes for shared mounts.
- Parallels itself takes a 5% slowdown on internal mounts and 20% slowdown on shared, when switching from its own to Apple's hypervisor.

My conclusion is that multipass's architecture for handling writes to shared mounts could be improved.

**Comment by Saviq** [comment]
Hi @arobertn, all,

> My conclusion is that multipass's handling of shared mounts could be significantly improved.

That is certainly the case. SSHFS was a safe choice for us simply because we can support it across the board. We do want to, where possible, to use hypervisor-native mounts to avoid the network / ssh overhead.

**Comment by y-hashida** [comment]
@Saviq 
Excuse me
How far along are you in resolving this issue?

**Comment by Saviq** [comment]
@y-hashida we're benchmarking the different choices now and will decide on what to do next in the next weeks.

**Comment by davibe** [comment]
Just to reiterate the importance of this. I am building a project on my M1 Mac (aya-rs/bpf-linker)

- using the multipass sshfs share : 1m20s
- outside of the same (local filesystem) : 8s
