### ISSUE TITLE
multipass for Windows 10 Home with Hyper-V enabled

### ISSUE THREAD

**Issue by jackjm** [canonical/multipass#1810]
I've verified on my Windows 10 Home 20H2, that Hyper-V can be enabled with the following script:

```
pushd "%~dp0"
dir /b %SystemRoot%\servicing\Packages\*Hyper-V*.mum >hyper-v.txt
for /f %%i in ('findstr /i . hyper-v.txt 2^>nul') do dism /online /norestart /add-package:"%SystemRoot%\servicing\Packages\%%i"
del hyper-v.txt
Dism /online /enable-feature /featurename:Microsoft-Hyper-V-All /LimitAccess /ALL
```

Hyper-V enabled on Windows 10 Home, verified
https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/915

I tried to install Multipass for Windows on the Hyper-V enabled Windows 10 Home, 
but the Hyper-V option is not available.

The Hyper-V option for Windows 10 Home should be available, since Hyper-V can be enabled,
maybe in an unnoticed advance option, as VirtualBox is still the go-to option for most Windows 10 Home users.

**Comment by Saviq** [comment]
Hi @jackjm, Hyper-V [isn't supported by Microsoft on Home editions](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v), sorry, but that means we can't support it in Multipass.

**Comment by madalinignisca** [comment]
Microsoft's documentation has not been updated everywhere.

For WSL2, Hyper-V is now a full option in Windows 10, since version 2004 and completely stable since 20H2.

With some tricks you can even get the management component, but that is not needed to be used.

You can enable experimental support on Windows Home, by doing checks if Windows 10 version is more recent than 2004.

**Comment by Saviq** [comment]
#1536 has some more discussion, FWIW.
