### ISSUE TITLE
Snapcraft using multipass from latest/edge results in "below requested/default size" error

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1926]
Hi,

Building snap using snapcraft with multipass from latest/edge (latest/edge: 1.7.0-dev.328+g8823c927)

results in

```
$ snapcraft
Launching a VM.
Build environment is in unknown state, cleaning first.
info failed: The following errors occurred:
instance "snapcraft-ubuntu-package-status" does not exist
launch failed: Available disk (221285634048 bytes) below requested/default size (274877906944 bytes)
An error occurred with the instance when trying to launch with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.
```

Reverting to latest/stable

```
sudo snap refresh multipass --channel=latest/stable
```

Allows snapcraft to proceed. I spoke to saviq on insternal chat who suspects this is due to the new checks that the requested space is available.

**Comment by Saviq** [comment]
Hey, yes, we're now checking that the requested disk space is available, but Snapcraft seems to be going extreme with the 256GB request to be on the safe side. We may need to introduce a `--force` flag or such, that will allow it to proceed.

I think we'll revert in the mean time.

**Comment by townsend2010** [comment]
Hmm, why is Snapcraft requesting a 256**GB** virtual disk?  That seems quite extreme and before we revert, perhaps we should ask the Snapcraft team why it is requesting so much disk space.

**Comment by Saviq** [comment]
The reason is that Snapcraft doesn't know what the build process will require for a particular snap. It may be extreme, sure, but it is Multipass that introduces a behaviour change that will result in breaking a huge percentage of Snapcraft workflows.

There may be things to improve on the Snapcraft side, sure (e.g. not request more than available space), but we should also allow benefiting from the fact the images are, in fact, sparse.

**Comment by townsend2010** [comment]
Ok, sure, I did not realize that Snapcraft has been requesting this disk size since 2018, so ok, we shouldn't release with this and break a bunch folks.  But we are in between a rock and a hard place when trying to guide a user on if they can allocate so much disk space to a VM wrt to the amount disk space available on their host.  We cannot account for sparse disk images in our computation of this.  At launch we can either restrict the size like the change introduced or let the user be on their own on managing free space on their host disk.

**Comment by ricab** [comment]
Can't we at least salvage the check and issue a warning? I know warnings are not shown by default in the CLI (that's something that could deserve separate reconsidering), but it would still be helpful. I have hit the no-disk situation multiple times and it's not easy to diagnose, since it fails in unexpected ways. A warning at launch would be helpful and could be complementary to the background checker you mentioned. 

Additionally, IMO we should refuse the launch when there isn't enough space for the `image_size`. With those two adaptations, the PR's would still be useful.
