### ISSUE TITLE
Mounts can't handle more than 256 open files

### ISSUE THREAD

**Issue by ricab** [canonical/multipass#1950]
**Describe the bug**
Trying to open more than 256 files from a Multipass mount fails, leaving the opening process stuck inside the instance and the mount otherwise unusable. Described in detail [here](https://github.com/canonical/multipass/issues/1933#issuecomment-770837840).

**To Reproduce**
How, and what happened?
1. `multipass start` (to get primary with a Home mount)
1. use the script attached to try to open more than 256 files, e.g. `python3 open-files.py .../multipass/3rd-party`
1. observe that it gets stuck after the 256th (sometimes 255th) file
    - to escape, do `multipass umount primary` on the host

**Expected behavior**
Multipass would support more then 256 simultaneous files. Failing that, a clear error would be produced.

**Additional info**
 - OS: both macOS and Ubuntu tried
 - Version 1.5

**Additional context**
  Found when investigating #1933. Lots more detail in there.

**Comment by ricab** [comment]
[open-files.zip](https://github.com/canonical/multipass/files/5904996/open-files.zip)

**Comment by townsend2010** [comment]
After some analysis, the issue is that we use the sftp server API in `libssh` and they have a hardcoded limit of 256 open handles to the sftp server.  In an experiment, that value was increased to 1024 and the issue "hang" issue no longer occurred and the non-obvious `EPERM` error was seen.

Since we have our own `libssh` branch, we can set this limit to a much higher arbitrary value to avoid this issue.  If a user does increase the open files limit higher than our arbitrary value, we'll error out in a much more graceful way.
