### ISSUE TITLE
multipass 1.6.2+win64: over-the-top settings for failure recovery

### ISSUE THREAD

**Issue by felixkasza** [canonical/multipass#2039]
The installer sets the `Multipass` service to blindly restart with a two-second delay. This might make sense for a service that might possibly recover through action elsewhere (e.g., diskspace being freed up, a network resource becoming available), but generally I consider it preferable to let the service process crash and figure out why it crashed.

Repro:
1. Install multipass 1.6.2+win64 on any supported Win10 release
1. `sc qfailure multipass` gives:
2. ```[SC] QueryServiceConfig2 SUCCESS

SERVICE_NAME: multipass
        RESET_PERIOD (in seconds)    : INFINITE
        REBOOT_MESSAGE               :
        COMMAND_LINE                 :
        FAILURE_ACTIONS              : RESTART -- Delay = 2000 milliseconds.```

Ideally, the installer would leave the failure settings at their defaults.

(As an aside: I couldn't find a way to lower the priority/importance of this bug when opening it. Please feel free to do so.)

**Comment by ricab** [comment]
Hi @felixkasza, we rely on the service restarting for some things (e.g. switching drivers). Actual crashes (forceful termination by the OS due to some violation) would be a bug and need investigation, but they might or might not reoccur after restarting. 

Multipass can also choose to exit if it finds that it doesn't have the necessary preconditions, but we can't know whether they will be fulfilled later on. We hope that they will, eventually, and so it makes sense to restart. Otherwise we'd need an additional manual step from users to get things going. Restarting the service should not remove information on earlier problems, so they can still be followed up. And when the requirements cannot be provided, users can manually disable (or ultimately uninstall).

Some special cases, like repeated crashes in a very short span, might need a different approach, but I think this is a generic problem best left to the OS. If I am not mistaken, we just install the service and get the defaults from Windows.

**Comment by felixkasza** [comment]
Hi @ricab,

and thanks for the explanation. If the recovery settings are an intentional choice, that's fine with me.

Cheers,
Felix.
