### ISSUE TITLE
Bash completion does not suggest options by itself

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#206]
I need to put the first hyphen in myself to get the completions:
```
$ multipass list<Tab><Tab>
# nothing
$ multipass list -<Tab><Tab>
--format   --help     --verbose
```
The same applies to `multipass info` - it only completes the instance name, not the `--format` option, for example.

**Comment by townsend2010** [comment]
Well, we have to be generic in how we either handle options or positional arguments.  So for the sake of trying to differentiate between the two, we require at least one hyphen to be typed in in order to suggest options.

A pitfall of bash completions, but we are better than `lxc` in which it *never* suggest options, no matter what you do.

**Comment by Saviq** [comment]
Would it be wrong to expose both positional args and options?

**Comment by townsend2010** [comment]
Hmm, since we usually don't have too many positional arguments for a given command, I suppose showing all positional arguments and options won't look too confusing to the user.  I'll experiment with this and see if it looks awkward.
