### ISSUE TITLE
`multipass launch --cloud-init` or `copy-files` do not complete file names

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#207]
```
$ multipass launch --cloud-init<Tab><Tab>
# nothing
```

**Comment by townsend2010** [comment]
For --cloud-init, I agree that we should complete file names.

However, for copy-files, there is no way for us to know when a user hits tab that they want to fill in an instance name or fill in file names which is why I left it to do nothing.  I guess the only thing I could do is if there is an instance name, then when the `:` is detected, it could present file names when tab is hit, but that will probably be tricky and may not be worth the effort.

**Comment by townsend2010** [comment]
The referenced branch fixes the --cloud-init part of this.  The copy-files part is much more tricky due to the issues mentioned in the above post.

**Comment by townsend2010** [comment]
For copy-files, the best I can probably do is something like this: https://pastebin.ubuntu.com/p/b4MRmVpmBz/

In that mess of files, 'test' is the running instance, so it's kind of hard to discover, but as long as you know some of the first letters of the instance name, then it should be ok to weed it out.  Also, the user will need to put in the `:` between the instance name and the file or directory.  What do you think?

**Comment by Saviq** [comment]
@townsend2010 for copy-files, I'd default to completing instance names unless none match, then I'd fall back to file names:
```
$ multipass copy-files <Tab><Tab>
instance-one  instance-two
$ multipass copy-files ./
file-one file-two
```
I wouldn't mix them, that's meh. Any case, that's icing on the cake, not a priority. File a new issue for copy-files?

**Comment by townsend2010** [comment]
@Saviq, cool, that works for me.  Yeah, let's open a new issue.
