### ISSUE TITLE
IDE or vscode can't connect Multipass using ssh, but in command line is fine.

### ISSUE THREAD

**Issue by Garithe** [canonical/multipass#2117]
**Describe the bug**

I created an account, modified /etc/ssh/sshd_config to allow PasswordAuthentication (default is no, I don't know why),  and then I could use ssh in command line on macOS to login.

Next step, I want to use things like vscode or pycharm to connect using ssh and try to  do some development on that. But neither worked. 

In vscode, it says:
Failed to parse remote port from server output
Terminating local server
Resolver error: Error: .......

In pycharm, simply says can't connect.

In command line, ssh username@ip works just fine.

I am using  the primary VM. Anyone has an idea about it?

**Comment by Saviq** [comment]
Hi @Garithe, if you can SSH from the command line, there has to be something wrong in the way you're configuring vscode / pycharm.

Password authentication is disabled by default on cloud images simply because key based auth is generally more secure, not to mention convenient.

https://stackoverflow.com/questions/55979701/how-do-i-resolve-failed-to-parse-remote-port-from-server mentions a similar issue to yours, maybe there's a clue?

**Comment by Garithe** [comment]
Sorry, ends up with stupid permission problems, I will close it@Saviq
