### ISSUE TITLE
sftp server: handle_stat: cannot stat

### ISSUE THREAD

**Issue by clubh** [canonical/multipass#2203]
The multipass log file (/Library/Logs/Multipass/multipassd.log) is suddenly exploding with gigabytes of entries like:

It appears like PHP is looping through include_paths and all failures to stat a file via sftp are logged. 

Any idea how to suppress or disable this logging ?

**Logs**
[2021-08-18T13:53:46.493] [error] [sftp server] handle_stat: cannot stat  '/Users/clu/www/phplib/file.class.php': no such file
[2021-08-18T13:53:46.493] [error] [sftp server] handle_stat: cannot stat  '/Users/clu/www/project/file.class.php': no such file

**Additional info**
 - macOS
- multipass 1.7.0+mac

Name:           localsrv
State:          Running
IPv4:           192.168.64.7
Release:        Ubuntu 16.04.7 LTS
Image hash:     ef5bafec76cc (Ubuntu 16.04 LTS)
Load:           0.21 0.11 0.09
Disk usage:     7.9G out of 9.6G
Memory usage:   300.1M out of 2.0G
Mounts:         /Users/clu/www => /www
                    UID map: 501:default
                    GID map: 20:default

**Comment by Saviq** [comment]
Hi @clubh, there's currently no way to do so, sorry.

You're right, we should reduce the severity of those messages, will let you know when there's a package available to test.

**Comment by surahman** [comment]
Hi @Saviq, I have had a quick look at the source code, what are your thoughts? I have not delved into this part of the codebase as of yet.

1) I think this can be achieved by adding a `base_log_level` data member to the `sftp_server` class and then performing a strict match check for the `level` at the log sites.  It might also be nice to allow `log_level`s above the `base_log_level` through.
2) I believe there might be a need for a `mpl::log_level::all` to allow all log messages through.
3) The check can be performed at the `mpl::log` call sites in `sftp_server` using an `if` statement. Due to the variability of the logging statements output, I do not believe delegating logging through a private method would work.
4) There will also need to be a CLI parameter added to the `Client` commands (which ones specifically require the `sftp_server`?) to set the `base_log_level` on the `sftp_server`.
5) There will be a need to send the `base_log_level` to the `Daemon` via RPC.

The same can be achieved for the `sftp_client` if required.

**Comment by Saviq** [comment]
@surahman hey, thanks for looking at this. It's actually just a case of changing the level of the different log calls as appropriate.

This particular case is here:

https://github.com/canonical/multipass/blob/69aeaebc1ace1506c5e88e4fa0a86cab1907c79b/src/sshfs_mount/sftp_server.cpp#L945-L946

This one should probably be dropped to `trace` level (the levels are defined in [multipass/logging/level.h](https://github.com/canonical/multipass/blob/69aeaebc1ace1506c5e88e4fa0a86cab1907c79b/include/multipass/logging/level.h)). It would make sense to review all the other uses in this file. If the status of the failed operation is forwarded through the SFTP connection, there's likely no point in logging an error there. `trace` level makes sense there for debugging of the SFTP server itself.

The level at which the daemon is logging is set via the `--verbosity` option (and we log at `debug` by default to have as much context as possible for bug reports).

The client also has `-v` that raises the logging level, and it also logs daemon messages while it's running.

**Comment by surahman** [comment]
Thank you @Saviq, I completely forgot about the verbosity flags on the `Client` which I had seen in the test batteries :facepalm:. I will review and downgrade all the forwarded error messages to `trace` and have a look at all other log statements as well.

**Comment by clubh** [comment]
Would downgrading to 1.6.2 solve this issue? Right now I am unable to use Multipass due to the excess logging.

**Comment by Saviq** [comment]
@clubh no, but you can try the package that will be published at the PR (#2207). I just triggered a build, will let you know when it's ready.

**Comment by Saviq** [comment]
@clubh you can download the package from here:

https://github.com/canonical/multipass/runs/3399923322

**Comment by clubh** [comment]
@Saviq Works perfectly, thanks.

**Comment by antego** [comment]
@Saviq the macos build is not accessible anymore, it says
```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>7ZVGE6P78B14FS4N</RequestId><HostId>tSaI5fEtuXsl7vlWAWHQMjwJ/PCG379w135t7uZQJ/MWnx8Lo6KOzRiNYEiAgL3CZYMfcYY2mlc=</HostId></Error>
```

Is there any other way of getting the package with the fix?

**Comment by Saviq** [comment]
@antego your can grab the RC here:

https://discourse.ubuntu.com/t/announcing-the-first-release-candidate-for-apple-m1-support/24445

**Comment by antego** [comment]
@Saviq beautiful, thank you! Love your work guys!
