### ISSUE TITLE
`multipass shell` creates "primary" vm

### ISSUE THREAD

**Issue by hatched** [canonical/multipass#2284]
**Describe the bug**
When running `multipass shell` without a name it assumes that the name is `primary`. Ok, but if no `primary` vm exists it creates one.

**To Reproduce**
1. delete any VM you have called `primary`.
1. `multipass shell`
1. note that it will create a new vm called `primary`.

**Expected behavior**
I would have expected it to fail with an error that either no name is provided or that primary doesn't exist. I'd prefer the former.

**Comment by ricab** [comment]
Hi @hatched. This is by design. It is intended as a quick way to access an Ubuntu instance. I understand that it may be unexpected and not to everyone's preference, but I assure you we discussed that and other pros and cons extensively before going with it. The behavior is documented in different places, like [online docs](https://multipass.run/docs/shell-command) and CLI help. It's even [featured in a video](https://snapcraft.io/multipass).

You can disable special treatment for the primary instance with `multipass set client.primary-name=`

I'm closing now, but please let us know if you find any inconsistencies.
