### ISSUE TITLE
[qemu] instances unreachable after daemon restart

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#2374]
```plain
$ mp launch
Launched: artistic-waterbear                                                    
$ mp exec artistic-waterbear -- uname -a
Linux artistic-waterbear 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ mp suspend artistic-waterbear
$ mp start artistic-waterbear
$ mp exec artistic-waterbear -- uname -a
Linux artistic-waterbear 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ snap stop multipass
Stopped.
$ snap start multipass
Started.
$ mp ls 
Name                    State             IPv4             Image
artistic-waterbear      Unknown           --               Ubuntu 20.04 LTS
```

And it's stuck like that.

The one reason that comes to mind is that we're releasing the IP on VM object destruction:
```plain
Dec 15 12:56:02 nuc dnsmasq-dhcp[53624]: DHCPRELEASE(mpqemubr0) 10.139.137.91 52:54:00:35:8d:1f               
```

So after the VM comes back, we don't know where it is.

[multipassd.log](https://github.com/canonical/multipass/files/7719496/multipassd.log)

**Comment by Saviq** [comment]
And we've identified the root cause - the `QemuVirtualMachine` destructor now releases the IP:

https://github.com/canonical/multipass/blob/d3a26d1ae902cc752a1631cbe79bf56fc5f876ca/src/platform/backends/qemu/qemu_virtual_machine.cpp#L217

**Comment by townsend2010** [comment]
In order to transition from a snap that has this bug to a fixed snap, there needs to be a way to get the instances to request a new IP lease.

One way that was suggested is to use the [`set_link`](https://qemu.readthedocs.io/en/latest/interop/qemu-qmp-ref.html#qapidoc-1308) QMP command and set the link down and then back up again.  The documentation says that not all network adapters support this, so I've been trying this out on all of the QEMU driver supported images.  In my tests, the `snapcraft:core` image does not support this and does not respond to `set_link`.

I'll investigate if there is another way that is supported by all images or if we will have to live with the fact that any `snapcraft:core` based images that are running will still not work after the upgrade.

**Comment by townsend2010** [comment]
Even doing an `ip link set tap-xxxxxx down` and then `ip link set tap-xxxxxx up` on the instance's tap device does not get the instance to request an IP lease.  I think we're stuck here.  I do think the good news is that most Snapcraft users don't build for `core` anymore, so the impact should be very minimal.

**Comment by LOGRUSFR** [comment]
> ... I think we're stuck here. I do think the good news is that most Snapcraft users don't build for `core` anymore, so the impact should be very minimal.

Hi,
Thank you for your work.
Alas, i had the same issue, dnsmasq never yielded any "DHCPPACK" line after last "DHCPRELEASE" and forced resume after snap refresh.
BTW, all my /var/snap/multipass/common/data/multipassd/network/* files are 0-sized.

On the other hand, succeded to launch my qemu image with virt-manager but been stopped by ssh key authentication (even if /home/ubuntu/authorized_keys file modification is feasible).

As i m not a snapcraft user, do you think possible to recover in multipass my image with a network workaround ?

**Comment by Saviq** [comment]
Hi @LOGRUSFR, have a look at https://github.com/canonical/multipass/issues/2371#issuecomment-989035709 - @townsend2010 explained there how to get rid of a suspend image.

**Comment by LOGRUSFR** [comment]
Hi @Saviq ,
Many thanks it worked like charm !
You put an end at a very long investigation (which missed this issue....) !  I hope i will help other users.
