### ISSUE TITLE
Possible to mount external ext4 disk into multipass VM on an M1 Mac?

### ISSUE THREAD

**Issue by demitri** [canonical/multipass#2380]
I have an external USB hard drive that has an ext4 filesystem. Is it possible to create a multipass VM and mount the disk for read/write into the VM? If not, is there another way I can read/write files to this disk via multipass?

I am running on an M1 Mac.

**Comment by Saviq** [comment]
Hi @demitri, there's currently no way to do that, no. #1897 has a request to allow hooking up host devices to the VMs. The problem is dealing with when things go wrong. What if the disk is disconnected?

We'll hopefully get to it in due time, but for now you'll have to mount the disk on your host and mount that with `multipass mount`.

I'll duplicate this to the other issue for now.

**Comment by duraki** [comment]
Can we contribute somehow on this feature? Seems like a nice stuff to add in Multipass.
