### ISSUE TITLE
[error] [client] Failed to set up autostart prerequisites: failed to link file

### ISSUE THREAD

**Issue by coffeekomrade** [canonical/multipass#2418]
**Describe the bug**
When running commands using mutipass in terminal on macOS, receive an error even though the action completes 

**To Reproduce**

```
<user>@slepnir ~ % multipass delete primary
[2022-01-30T08:54:01.108] [error] [client] Failed to set up autostart prerequisites: failed to link file '/Users/<user>/Library/LaunchAgents/com.canonical.multipass.gui.autostart.plist' to '/Library/Application Support/com.canonical.multipass/Resources/com.canonical.multipass.gui.autostart.plist'
<user>@slepnir ~ % multipass list
[2022-01-30T08:54:16.162] [error] [client] Failed to set up autostart prerequisites: failed to link file '/Users/<user>/Library/LaunchAgents/com.canonical.multipass.gui.autostart.plist' to '/Library/Application Support/com.canonical.multipass/Resources/com.canonical.multipass.gui.autostart.plist'
Name                    State             IPv4             Image
primary                 Deleted           --               Not Available
<user>@slepnir ~ % multipass purge
[2022-01-30T08:54:24.645] [error] [client] Failed to set up autostart prerequisites: failed to link file '/Users/<user>Library/LaunchAgents/com.canonical.multipass.gui.autostart.plist' to '/Library/Application Support/com.canonical.multipass/Resources/com.canonical.multipass.gui.autostart.plist'
<user>@slepnir ~ % multipass list 
[2022-01-30T08:54:27.186] [error] [client] Failed to set up autostart prerequisites: failed to link file '/Users/<user>/Library/LaunchAgents/com.canonical.multipass.gui.autostart.plist' to '/Library/Application Support/com.canonical.multipass/Resources/com.canonical.multipass.gui.autostart.plist'
No instances found.
<user>@slepnir ~ % 

```
**Expected behavior**
No error 

**Logs**
[multipassd.log](https://github.com/canonical/multipass/files/7966036/multipassd.log)

**Additional info**
 - `macOS 12.2 (Intel Mac)`
- `1.8.1+mac`
- `multipass info --all` < Receive same error as above, shows no info

**Comment by Saviq** [comment]
Hi @coffeekomrade, what's your output of:

```plain
$ ls -ld ~/Library/LaunchAgents/
$ ls -l ~/Library/LaunchAgents/
```

**Comment by protosam** [comment]
This is being blocked by a Mac OS security feature and for good reason. 

There are additional baked in security features regarding [launch agents](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html)

```
$ ls -ld ~/Library/LaunchAgents/
drwxr-xr-x@ 3 protosam  staff  96 Dec  4 16:55 /Users/protosam/Library/LaunchAgents/

$ ls -l ~/Library/LaunchAgents/
total 0

$ echo hello > ~/Library/LaunchAgents/com.canonical.multipass.gui.autostart.plist
-bash: /Users/protosam/Library/LaunchAgents/com.canonical.multipass.gui.autostart.plist: Operation not permitted

sudo bash -c 'echo hello > ~/Library/LaunchAgents/com.canonical.multipass.gui.autostart.plist'
bash: line 1: /Users/protosam/Library/LaunchAgents/com.canonical.multipass.gui.autostart.plist: Operation not permitted

$ sudo su - 

root# bash -c 'echo hello > ~protosam/Library/LaunchAgents/com.canonical.multipass.gui.autostart.plist'
bash: line 1: /Users/protosam/Library/LaunchAgents/com.canonical.multipass.gui.autostart.plist: Operation not permitted
```

**Comment by protosam** [comment]
Something more that I don't understand is why it's trying to create it when I told it "no":

```
$ multipass set client.gui.autostart=false
[2022-03-13T23:42:22.299] [error] [client] Failed to set up autostart prerequisites: failed to link file '/Users/protosam/Library/LaunchAgents/com.canonical.multipass.gui.autostart.plist' to '/Library/Application Support/com.canonical.multipass/Resources/com.canonical.multipass.gui.autostart.plist'

$ multipass get client.gui.autostart=false
[2022-03-13T23:42:26.485] [error] [client] Failed to set up autostart prerequisites: failed to link file '/Users/protosam/Library/LaunchAgents/com.canonical.multipass.gui.autostart.plist' to '/Library/Application Support/com.canonical.multipass/Resources/com.canonical.multipass.gui.autostart.plist'
Unrecognized settings key: 'client.gui.autostart=false'

```

**Comment by protosam** [comment]
It's probably [Gatekeeper](https://en.wikipedia.org/wiki/Gatekeeper_(macOS))? Pretty sure there has been a default since Catalina where the xattr of `com.apple.quarantine` is placed on `~/Library/LaunchAgents`. I have no intention of changing this on my system.

If  a user wants an application to start up automatically, they can add it to their "Login Items" in their "Users & Groups" settings. Applications should not automatically try to create launch agents, it's the entire reason the xattr has been placed on the directory by default.

I think the attempt at symlinking a launch agent should be removed as default global behavior from the CLI.

**Comment by protosam** [comment]
Actually... it's not due to xattr. Smells like [System Integrity Protection](https://en.wikipedia.org/wiki/System_Integrity_Protection). I have no clue to see what directories it is configured for though, `csrutil status` just tells you if it's enabled.

**Comment by protosam** [comment]
Deleted prior updates, think they were actually just wrong. It was bothering me that I couldn't articulate and prove /why/ I couldn't read/write that directory. So I dug into it more. 

Looks like in my case I may have actually done the Mac equivalent of `chattr +i ~/Library/LaunchAgents` to squash Chrome's obsessive compulsion with adding crap to that directory at some point (found the steps in my setup notes).

When looking at file immutability, I was stuck because in linux we have `+i`. Mac has `uchg` (users) and `schg` (super users). This is visible with `ls -lOd` (letter O, not zero 0).

```
$ ls -lOd ~/Library/LaunchAgents/
drwxr-xr-x@ 2 protosam  staff  schg 64 Mar 14 12:14 /Users/protosam/Library/LaunchAgents/
```

It's immutable, because `schg`. To remove these attributes, you have to use `nouchg` and `noschg`. For the schg attribute, it has to be ran by root.

```
$ sudo chflags -R noschg ~/Library/LaunchAgents/
Password: [allyourbasearebelongtous]

$ ls -lOd ~/Library/LaunchAgents/
drwxr-xr-x@ 2 protosam  staff  - 64 Mar 14 12:14 /Users/protosam/Library/LaunchAgents/

$ sudo chflags -R schg ~/Library/LaunchAgents/

$ ls -lOd ~/Library/LaunchAgents/
drwxr-xr-x@ 2 protosam  staff  schg 64 Mar 14 12:14 /Users/protosam/Library/LaunchAgents/
```

Multipass is trying to create launch agents on devices without user consent for the GUI, which isn't even functionally necessary to use multipass.

I think this behavior on MacOS should be changed.

If a user wants a GUI application to start on login, they can open up `System Preferences > Users & Groups > Click their User > Click the Login Items tab > Click the [+] icon` and add the app to launch when they login.

If the convenience of adding the launch agent is necessary, it should be by prompt-only.

**Comment by ricab** [comment]
This is about to change with the new GUI, which will have a separate mechanism for autostart. We'll still need to rely on LaunchAgents, but the error in the OP is going away.
