### ISSUE TITLE
Can't access VM's from inside WSL2 on Windows

### ISSUE THREAD

**Issue by h00jraq** [canonical/multipass#2590]
**Describe the bug**
I'm trying to create some VM's with mutlipass and access them from inside WSL2 on my Windows 10.
What I want to achieve is to setup SWARM nodes using multipass and manage those from my WSL2 Ubuntu
I can't ping any of created VM's 

**To Reproduce**
How, and what happened?
```
PS C:\Users\fdrzewiecki_wa> multipass set local.bridged-network=ExternalSwitch
PS C:\Users\fdrzewiecki_wa> multipass launch --bridged
Launched: endless-sow

PS C:\Users\fdrzewiecki_wa> multipass networks
Name            Type      Description
Default Switch  switch    Virtual Switch with internal networking
Ethernet        ethernet  Intel(R) Ethernet Connection (14) I219-V
Ethernet 6      ethernet  Dell Giga Ethernet
ExternalSwitch  switch    Virtual Switch with external networking via "Ethernet"
WSL             switch    Virtual Switch with internal networking
WiFi            wifi      Intel(R) Wi-Fi 6E AX210 160MHz

PS C:\Users\fdrzewiecki_wa> multipass list
Name                    State             IPv4             Image
endless-sow             Running           172.19.63.199    Ubuntu 20.04 LTS
node                    Running           172.19.56.201    Ubuntu 20.04 LTS
node1                   Running           172.19.49.155    Ubuntu 20.04 LTS
quality-jerboa          Running           172.19.55.124    Ubuntu 20.04 LTS
                                          172.19.52.250
PS C:\Users\fdrzewiecki_wa>

fdrzewiecki@9BG9HG3:~$ ping 172.19.48.1
PING 172.19.48.1 (172.19.48.1) 56(84) bytes of data.
^C
--- 172.19.48.1 ping statistics ---
18 packets transmitted, 0 received, 100% packet loss, time 17656ms
```
**Expected behavior**
I would like to be able to ping and access VM's from inside WSL2

**Additional info**
```
 - OS: Windows 10 Enterprise 19044.1586
- `C:\Users\fdrzewiecki>multipass version
multipass   1.9.0+win`
- `PS C:\Users\fdrzewiecki_wa> multipass info --all
Name:           endless-sow
State:          Running
IPv4:           172.19.63.199
Release:        Ubuntu 20.04.4 LTS
Image hash:     9a0f10025864 (Ubuntu 20.04 LTS)
Load:           0.00 0.00 0.00
Disk usage:     1.3G out of 4.7G
Memory usage:   433.8M out of 912.5M
Mounts:         --

Name:           node
State:          Running
IPv4:           172.19.56.201
Release:        Ubuntu 20.04.4 LTS
Image hash:     9a0f10025864 (Ubuntu 20.04 LTS)
Load:           0.00 0.00 0.00
Disk usage:     1.3G out of 4.7G
Memory usage:   417.1M out of 912.5M
Mounts:         --

Name:           node1
State:          Running
IPv4:           172.19.49.155
Release:        Ubuntu 20.04.4 LTS
Image hash:     9a0f10025864 (Ubuntu 20.04 LTS)
Load:           0.88 0.18 0.06
Disk usage:     1.3G out of 4.7G
Memory usage:   395.7M out of 912.5M
Mounts:         --

Name:           quality-jerboa
State:          Running
IPv4:           172.19.55.124
                172.19.52.250
Release:        Ubuntu 20.04.4 LTS
Image hash:     9a0f10025864 (Ubuntu 20.04 LTS)
Load:           0.00 0.00 0.00
Disk usage:     1.3G out of 4.7G
Memory usage:   415.6M out of 912.5M
Mounts:         --l`
```
**Additional context**

**Comment by KazimESEN** [comment]
Enabling Virtualization in VirtualBox and VMware
Ubuntu 22.04 guest OS installed on vmware or virtualbox running on Windows 10 cannot start because the multipass CPU does not support virtualization during installations in kubernetes tutorial.

By running Powershell or CMD.exe with Administrator rights in Windows 10;
      systeminfo
For Windows 10, the host's information about virtualization is displayed with the command.
Hyper-V Requirements:  Virtualization Enabled In Firmware: Yes
In the field of virtualization; If Yes or Enabled; in the cd C:\Program Files\Oracle\VirtualBox directory;
     VBoxManage modifyvm <VirtualMachineName> --nested-hw-virt on
It is solved by running the command, it was already solved when Hyper-V was turned off in vmware.

If No or Disabled, it is enabled from BIOS or UEFI and Hyper-V is disabled;
bcdedit /set hypervisorlaunchtype off
HyperV is turned off with the command, after this command restart is required. 

To remove HyperV feature in Windows 10;
DISM /Online /Disable-Feature /All /FeatureName:Microsoft-Hyper-V
Or
Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-Hypervisor

bcdedit in the command output; It should be "hypervisorlaunchtype Off".

**Comment by KazimESEN** [comment]
Enabling Virtualization in VirtualBox and VMware
Ubuntu 22.04 guest OS installed on vmware or virtualbox running on Windows 10 cannot start because the multipass CPU does not support virtualization during installations in kubernetes tutorial.
  
By running Powershell or CMD.exe with Administrator rights in Windows 10;
systeminfo
For Windows 10, the host's information about virtualization is displayed with the command.
Hyper-V Requirements:  Virtualization Enabled In Firmware: Yes
In the field of virtualization; If Yes or Enabled; in the cd C:\Program Files\Oracle\VirtualBox directory;
VBoxManage modifyvm <VirtualMachineName> --nested-hw-virt on
It is solved by running the command, it was already solved when Hyper-V was turned off in vmware.
If No or Disabled, it is enabled from BIOS or UEFI and Hyper-V is disabled;
bcdedit /set hypervisorlaunchtype off
HyperV is turned off with the command, after this command restart is required. To remove HyperV feature in Windows 10;
DISM /Online /Disable-Feature /All /FeatureName:Microsoft-Hyper-V
Or
Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-Hypervisor

bcdedit in the command output; It should be "hypervisorlaunchtype Off".

**Comment by potoo0** [comment]
## Temporary / Experimental Workaround for WSL2 → Multipass VM Access Issue After Windows Reboot

**Context:**  
After a Windows restart, WSL2(networkingMode=mirrored) could no longer access Multipass VMs via their IP addresses.

```
❯ ip route
default via 198.18.0.2 dev eth0 proto kernel
...
172.24.0.0/16 dev br-206dea06edb9 proto kernel scope link src 172.24.0.1 linkdown
...

❯ ping node1
PING node1 (172.24.10.63) 56(84) bytes of data.
From DESKTOP-F6O165R (172.24.0.1) icmp_seq=1 Destination Host Unreachable
```

**Observation:**
Disabling the virtual bridge interface br-206dea06edb9 inside WSL2 restored connectivity:

```
❯ sudo ip link set br-206dea06edb9 down

❯ ping node1
PING node1 (172.24.10.63) 56(84) bytes of data.
64 bytes from node1 (172.24.10.63): icmp_seq=1 ttl=64 time=25.7 ms
64 bytes from node1 (172.24.10.63): icmp_seq=2 ttl=64 time=1.09 ms
64 bytes from node1 (172.24.10.63): icmp_seq=3 ttl=64 time=1.60 ms
```
