### ISSUE TITLE
Multipass should accept decimals back for memory values

### ISSUE THREAD

**Issue by larstobi** [canonical/multipass#2677]
**Describe the bug**
Describe what your problem is.

When retrieving the memory size of an instance using "get", the number returned is a float with one decimal place, of which the decimal is always zero.

**To Reproduce**
How, and what happened?
1. `multipass get local.example.memory`
1. It returns "`256.0MiB`".

**Expected behavior**
What did you expect to happen?

That it returns "`256M`" or "`256MiB`".

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: macOS 12.4
- `multipass version` 1.10.1
- `multipass info --all`
```
Name:           example
State:          Stopped
IPv4:           --
Release:        --
Image hash:     e1ce033239f0 (Ubuntu 22.04 LTS)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --
```

**Additional context**
Trying to set back the same number, results in an error:
```

multipass set local.example.memory=256.0MiB
set failed: Invalid setting 'local.s1.memory=256.0MiB': 256.0MiB is not a valid memory size - need a non-negative integer (in base 10) followed by the desired unit (e.g. 1234B, 42MiB)

```
Dropping the `.0` decimal works:
`multipass set local.example.memory=256MiB`

I don't know C++, but to me this looks like where it is done: https://github.com/canonical/multipass/blob/v1.10.1/src/utils/memory_size.cpp#L130-L131

**Comment by ricab** [comment]
Hi @larstobi, it is intentional that it returns a decimal. For larger units, rounding to the integer would be too coarse. It didn't feel right to say 2GiB instead of 1.5GiB as that's off by a third and half a gig is significant. And we shouldn't have to say 1234MiB either, because those last digits become insignificant.

However, I agree that it is inconsistent for Multipass not to take decimal values back too. This is something that we [have planned](https://github.com/canonical/multipass/projects/14#card-79444697) but didn't get to yet. 

So thank you for pointing it out. I hope you don't mind me repurposing your report accordingly :slightly_smiling_face:

**Comment by larstobi** [comment]
Thanks for getting back to me. I'm making a Terraform provider plugin for multipass, and being able to compare what's launched and what's in the desired Terraform configuration is vital. But as long as the multipass output is not rounded and has lost accuracy, I can handle it by internally converting it to the same format. It is so that the output is not lossy? Thanks for helping me out on this. :-)

**Comment by larstobi** [comment]
In fact, it would have been best to use the `multipass info example --format json` total memory output which apparently is in bytes, but I haven't been able to convert the output from `info.example.memory.total` to anything I recognize from the `launch` parameters.

For instance, if I launch with 256MiB then the `info` output is `218558464`.  But: `218 558 464 bytes = 208,433594 MiB`. So, I have to stick with what I get from `multipass get local.example.memory` until I figure out how to convert that to MiB.

**Comment by ricab** [comment]
> It is so that the output is not lossy?

Sorry, I am afraid not, we report it back rounded. There's a TODO to get it back in bytes when `--raw` is given, but not yet done. In the meantime, you *could* look at the settings file, where we record it in bytes, but that is an implementation detail that I don't advise depending on.

> [...] but I haven't been able to convert the output from `info.example.memory.total` to anything I recognize from the `launch` parameters.

Right. That's because what we report in `info` is not what we requested but what the OS actually gives us, as per `/proc/meminfo`. From `man proc`, the memory total is *Total usable RAM (i.e., physical RAM minus a few  reserved  bits  and  the  kernel  binary code).*

Would you perhaps be able to work with approximations and check that the difference between what's requested and obtained is smaller than an acceptable threshold?

**Comment by larstobi** [comment]
Ah, yes, the `mem_size` field in `multipassd-vm-instances.json` actually has it in bytes. That would be ideal.

Getting rounded memory size numbers is certainly not going to work well if there actually is loss, since it would cause a difference between wanted state and current state, and thus the instance to be modified. However, as long as people don't put weird memory size numbers in there, I think rounding with loss is unlikely to occur (i.e. 1,5 GiB to bytes and back to MiB or GiB does not cause rounding loss).

I don't want to add too much code that compares slightly different memory sizes, and also, perhaps the user wanted to decrease memory by a slight amount, so I think I'll keep going assuming no loss, and wait for the "--raw" output. Thanks! :-)

**Comment by sharder996** [comment]
Hello @larstobi, a PR has been accepted for adding the ability to use decimals and should be in `edge` if you need it immediately. I know that a secondary point of this thread was to add a `--raw` flag, but that would require a bit of engineering to design how we want to do it. Since the original request was to allow decimal amounts and which has been fulfilled, I'm going to leave this issue closed. If you want the "`--raw`" enhancement, please open a new issue.

Thanks!
