### ISSUE TITLE
Missing socket

### ISSUE THREAD

**Issue by gotgouda** [canonical/multipass#2729]
I downloaded multipass but cannot create an instance.  Have tried a couple different ways to troubleshoot off of different forums, but I get an error message that: 

ubuntu@primary:~$ multipass shell
launch failed: cannot connect to the multipass socket                           
Please ensure multipassd is running and '/var/snap/multipass/common/multipass_socket' is accessible

I'm running Mac OS Monterrey version 12.5.1
Not sure if I have hyperkit or another program.  So far no issues with my Virtual Box VM.

**Additional info**
 - OS: [e.g. macOS 10.15]
- `multipass version`
- `multipass info --all`
- `multipass get local.driver`

**Additional context**

**Comment by luis4a0** [comment]
Hi @gotgouda, can you please send us the outputs in "Additional info" above? It would be nice if you can also send us the [logs](https://multipass.run/docs/accessing-logs#heading--macos). Thanks!

**Comment by gotgouda** [comment]
Hi, what I pasted was the output. Please refer to screenshot of bash CLI.  There are no logs accessible because I do not have a password for an instance nor can I set one even by trying to create an ssh tunnel.  Pretty sure my issue is the socket that isn't allowing me to create an instance, but not sure what the work around is.  
![Multipass bash shell 1](https://user-images.githubusercontent.com/112450035/187509753-bae40205-8db0-4c32-b4d2-bfbc55033e43.jpeg)

**Comment by townsend2010** [comment]
Hey @gotgouda,

You are trying to run Multipass inside the already existing Multipass instance.  Is this what you are intending?

Also, please provide the output of `multipass get local.driver` from your **macOS** host.  If you are using the `hyperkit` driver, then nesting does not work which is why Multipass will not run inside the Multipass instance.

**Comment by gotgouda** [comment]
So this might be then a misunderstanding with the tutorials off of the Ubuntu website.  I downloaded the program, but have no GUI access that I can find.  When I click on the application icon in my MacOS it opens a small icon on my top tool bar, and from there it opens the shell.  I am wanting Multipass so I get more practice with my command line programming, but when I follow the tutorials it gives me these errors.  I can keep going through the tutorials and skip the ones with the multipass command, but then other issues like no password, etc come up.  Not sure how I can effectively go through the tutorials.

**Comment by townsend2010** [comment]
Hi @gotgouda,

Since you are on a macOS host, you can follow the tutorial at https://multipass.run/docs/mac-tutorial.

But by clicking "Open Shell" in the drop down menu, it automatically creates a `primary` instance with a shell opened into the instance itself.  If you are wanting to do `multipass` commands, then you need to open a Mac terminal and from there you will be able to issue the commands such as `info`, `mount`, etc.

Hope this helps and good luck!

**Comment by gotgouda** [comment]
Yeah, that was the issue.  Thanks for your help.
