### ISSUE TITLE
[regression][snap] Existing xenial images will not start after upgrading to 1.11.0RC

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#2796]
Upgrading to 1.11.0RC will cause any existing Xenial instances to not boot.  This is due to the `qemu` driver *only* supporting UEFI booting on fresh starts.

Multipass needs to consider existing Xenial instances when starting.

**Comment by xnox** [comment]
Note that xenial supports mixed UEFI & Bios boot. Are xenial instances have been launched using the wrong base image which is not future proof? back in xenial streams we have two image types bios and bios+uefi, with all later series switched to just providing bios+uefi image type.

**Comment by townsend2010** [comment]
@xnox,

Yes, the wrong base image was chosen to launch Xenial instances all this time, (the `disk1.img` image).  I was not aware the `uefi.img` image could even boot both types until now.  At any rate, I have a fix for handling our broken case and now need to fix our streams and image handling to download the `uefi.img` image even if `disk1.img` exists in our cache.

**Comment by xnox** [comment]
@townsend2010 note that image types/names are different between releases.

originally xenial launched with two images bios and bios+uefi because at the time there were clouds that would fail to boot and get confused by the bios+uefi image. Over time, all of them got fixed, thus bionic and later only have bios+uefi image. With suffixes across all of them being differet.

So on xenial one should use `.uefi.img`, and on bionic+ one should use `.img`

And do reconfirm with ~Public Cloud (cpc) people.

**Comment by townsend2010** [comment]
Hey @xnox,

Got it, thanks!  It's too bad we were unaware all this time that the old `uefi` images supported both UEFI **and** BIOS.  Oh well....
