### ISSUE TITLE
feat: ability for third party apps to connect to docker.sock

### ISSUE THREAD

**Issue by lucasgonze** [canonical/multipass#3021]
**What are you trying to do?**

Allow third party apps trying to connect to Docker's VM to connect to the Docker VM within Multipass.

**What's your proposed solution?**

Run a daemon on `unix:///var/run/docker.sock`

**Additional context**

Applications attempting to launch a Docker instance throw an error, such as supabase in the following:

```
$ supabase start -x imgproxy,storage-api,studio
Error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
  in github.com/supabase/cli/internal/utils.AssertDockerIsRunning:48
  in github.com/supabase/cli/internal/start.Run:36
Try rerunning the command with --debug to troubleshoot the error.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

System context: Apple M1 on Ventura 13.2

**Comment by andrei-toterman** [comment]
Hi, @lucasgonze! While this specific feature is outside the scope of Multipass itself, I think you could still accomplish it by forwarding the Unix socket through ssh from the instance to the host by doing something like `ssh -nNT -L /var/run/docker.sock:/var/run/docker.sock <user>@<instance_ip>`. But for this you'll need to add your own ssh keys to the instance in order to connect to it without `multipass shell`. I hope this helps!

**Comment by andrei-toterman** [comment]
Alternatively, you could also configure `dockerd` inside the instance to listen to a TCP socket, according to https://docs.docker.com/config/daemon/remote-access/
Then, you can do `export DOCKER_HOST=<instance_ip>:<docker_port>` in your host and `supabase` should be able to connect to it

**Comment by lucasgonze** [comment]
Thanks, @andrei-toterman ! I appreciate the tips.
