### ISSUE TITLE
"start failed: The following errors occurred: argument not found" when starting instance

### ISSUE THREAD

**Issue by soredake** [canonical/multipass#3031]
**Describe the bug**
Instance takes too long to start and then prints this:
```
start failed: The following errors occurred:
argument not found

[process exited with code 2 (0x00000002)]
```
When i start new tab with multipass i can use my instance fine, but error will show up again after stopping and restarting instance.

**To Reproduce**
How, and what happened?
1. `multipass start primary`

**Expected behavior**
No errors.

**Logs**
[log.txt](https://github.com/canonical/multipass/files/11210272/log.txt)

**Additional info**
 - OS: Windows 11 Pro
- `multipass   1.12.0-rc.498+g46040331.win
multipassd  1.12.0-rc.498+g46040331.win`
- `info failed: fish: Expected a variable name after this $.
df --output=used $(sudo fdisk -l | grep 'Linux filesystem' | awk '{print $1}') -B1 | sed 1d`
- `virtualbox`

**Additional context**

**Comment by sharder996** [comment]
Hi @soredake, sorry for the late reply! 
It looks like one of our bash commands for getting info about the instance is failing and timing out causing the long delay. We have made some tweaks to this particular command since then which should be in the updated Windows installer package for 1.12.0-rc. If you could try out the new package and let us know if the issue persists or not that would be great!

**Comment by soredake** [comment]
@sharder996 yes, now i don't see this error, thank you!
