### ISSUE TITLE
running multipass shell with multiple instances selects first VM, and it's in unknown state

### ISSUE THREAD

**Issue by Awildanthony** [canonical/multipass#3106]
**Description:**
Hi! I have been using `multipass` for a few weeks and am in a learning process with Virtual Machines and firewalls. When trying to run `multipass shell` with no additional arguments, I get the error `shell failed: Cannot retrieve credentials in unknown state`. I suspect the intended behavior with no additional arguments would be to select the first VM that appears; in my case, it is in an unknown state:

```sh
anthonymalysz@Anthonys-Air ~ % multipass list
Name                            State               IPv4                   Image
primary                         Unknown              --               Ubuntu 22.04 LTS
agile-turnstone                 Unknown              --               Ubuntu 22.04 LTS
immaculate-fennec               Deleted              --               Not Available
my-vm                           Running         192.168.64.4          Ubuntu 22.04 LTS
topical-coati                   Unknown              --               Ubuntu 22.04 LTS
```
 ...and hence the error. As of yesterday, running `multipass shell` allowed me to use the `primary` instance without any problems; I'm not sure if this is relevant, but I did update to the newest version of MacOS Ventura since the last time I used `multipass`. I'm also not sure which of those instances were there to begin with, or if I (un)mistakenly added them in my experimentation.

**Solution?**
I'm referencing everything from seeing this portion of the source code:

https://github.com/canonical/multipass/blob/02d5c5eb84d1059cc2d15a84b434a52528ceafd7/src/client/cli/cmd/shell.cpp#LL55C53-L55C53

Running `multipass shell my-vm` works, but I was mostly just curious as to why `primary` is now in an unkown state, and how to resolve it (if this isn't actually a bug - I couldn't find any other relevant reports). Thanks!

**Mac:**
Ventura 13.4

**Multipass Version:**
multipass   1.10.1+mac
multipassd  1.10.1+mac

**Comment by ricab** [comment]
Hi @Awildanthony, the primary instance is listed first when doing `multipass list` (if it exists). As you found, with no arguments, the `shell` command tries to open a shell in the primary instance, starting or launching it if necessary. That is all as intended.

The problem is really with the instances in the Unknown state. That state indicates instances appear to start normally but Multipass can't determine their IP for some reason (most likely, the instance failed to obtain one by DHCP).

What does `multipass get local.driver` say? If it says `hyperkit`, one thing to try is to delete stale entries from `/var/db/dhcpd_leases`:

1. Stop the multipass daemon with `sudo launchctl unload /Library/LaunchDaemons/com.canonical.multipassd.plist`
2. Edit `/var/db/dhcpd_leases` removing any entries with the same names as your instances
3. Start the multipass daemon with `sudo launchctl load /Library/LaunchDaemons/com.canonical.multipassd.plist`
4. Start or shell into the instance you need

Be sure also to have a look at our [network troubleshooting docs](https://multipass.run/docs/troubleshoot-networking#heading--generic-networking-problems).

**Comment by aj-stein-nist** [comment]
Hi @ricab, Anthony and I work together and we are making great use of multipass. What a nice tool, thanks for the work of you and the team.

I will try this with Anthony eventually. I had also asked him to make the issue and pose for consideration an idea, whether it is a feature request or is an admittedly niche bug request: would it not be beneficial to to look for the first running instance that is not in an `Unknown` or `Stopped` state when executing the `multipass shell` argument without any parameters and select the first OK running one first if not explicitly selecting an instance?
