### ISSUE TITLE
Can`t start instance

### ISSUE THREAD

**Issue by shatll-s** [canonical/multipass#3111]
Hi! I can\`t start one instance with Unknown state. There are no problems with the rest.

After trying to start instance, i get endless wait and then error
start failed: The following errors occurred:                                    
Instance 'chinet1804' is already running, but in an unknown statechinet1804: timed out waiting for response

I don`t know how to reproduce it.
![Screenshot_20230606_131027](https://github.com/canonical/multipass/assets/37956983/f9155954-148a-48a0-9583-261ec5cc4c46)

> "chinet1804": {
        "deleted": false,
        "disk_space": "5368709120",
        "extra_interfaces": [
        ],
        "mac_addr": "52:54:00:0e:c3:e6",
        "mem_size": "8589934592",
        "metadata": {
            "arguments": [
                "-bios",
                "OVMF.fd",
                "--enable-kvm",
                "-cpu",
                "host",
                "-nic",
                "tap,ifname=tap-4dcc96ac795,script=no,downscript=no,model=virtio-net-pci,mac=52:54:00:0e:c3:e6",
                "-device",
                "virtio-scsi-pci,id=scsi0",
                "-drive",
                "file=/home/user/multipass/data/vault/instances/chinet1804/ubuntu-18.04-server-cloudimg-amd64.img,if=none,format=qcow2,discard=unmap,id=hda",
                "-device",
                "scsi-hd,drive=hda,bus=scsi0.0",
                "-smp",
                "1",
                "-m",
                "8192M",
                "-qmp",
                "stdio",
                "-chardev",
                "null,id=char0",
                "-serial",
                "chardev:char0",
                "-nographic",
                "-cdrom",
                "/home/user/multipass/data/vault/instances/chinet1804/cloud-init-config.iso"
            ],
            "machine_type": "pc-i440fx-kinetic",
            "mount_data": {
            }
        },
        "mounts": [
        ],
        "num_cores": 1,
        "ssh_username": "ubuntu",
        "state": 2
    },

**Comment by shatll-s** [comment]
@luis4a0, thank you for participating.
It took much time, successfully restarted, but the problem still stays

![Screenshot_20230606_172402](https://github.com/canonical/multipass/assets/37956983/5c46ffd0-e560-446a-9941-50d359c517d2)
restart log: [logs.txt](https://github.com/canonical/multipass/files/11665738/logs.txt)

**Comment by shatll-s** [comment]
Any suggestions?
I checked again - all other instances are running normally

**Comment by luis4a0** [comment]
Hi @shatll-s, it seems you have some corruption on the machine. But, unfortunately, the log ends when the snap is restarted. Is it possible to have the logs starting at the restart? Thanks!

**Comment by shatll-s** [comment]
Hi @luis4a0, maybe you can look at my log if you have time? Thx

**Comment by luis4a0** [comment]
Hi @shatll-s, unfortunately I wasn't notified on your previous answer; I am very sorry about that.

We examined the log and concluded that the `suspend` image is corrupted because the instance or the host was busy when suspending, thus taking more time than expected and aborting the operation after a timeout was reached (we increased this timeout in 1.12.0 in order to allow more time to instances to resume from suspend).

To recover the instance, the image can be recovered with the following procedure:
1. stop the daemon with `sudo snap stop multipass.multipassd`
2. `/snap/multipass/current/usr/bin/qemu-img snapshot -d suspend /home/user/multipass/data/vault/instances/chinet1804/ubuntu-18.04-server-cloudimg-amd64.img`
3. restart the daemon with `sudo snap start multipass.multipassd`

After this procedure, the instance should be listed as stopped in `multipass list`. Please let us know how this goes. Good luck!

**Comment by shatll-s** [comment]
> * stop the daemon with `sudo snap stop multipass.multipassd`
> 
> * `/snap/multipass/current/usr/bin/qemu-img snapshot -d suspend /home/user/multipass/data/vault/instances/chinet1804/ubuntu-18.04-server-cloudimg-amd64.img`
> 
> * restart the daemon with `sudo snap start multipass.multipassd`

It helps, thank you!!!

**Comment by luis4a0** [comment]
Great news @shatll-s! I'm closing the ticket, then. Don't hesitate in reopening if you encounter more issues. Thanks!
