### ISSUE TITLE
arm-none-eabi-gcc is very slow on multipass

### ISSUE THREAD

**Issue by hussainaloum** [canonical/multipass#3292]
**Describe the bug**
Multipass is very slow when compiling C code using arm-none-eabi-gcc 10.3-2021.10

**To Reproduce**
How, and what happened?
1. Use to compile any large c code using arm-none-eabi-gcc 10.3-2021.10

**Expected behavior**
I expect the compilation process to be as fast as my native OS or close

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

**Additional info**
 - OS: MacOS 14.1
- `multipass version 1.12.2+mac`
- `multipass info --all`
Name:           primary
State:          Running
IPv4:           192.168.64.10
Release:        Ubuntu 22.04.3 LTS
Image hash:     5bed3f233c24 (Ubuntu 22.04 LTS)
CPU(s):         4
Load:           0.08 0.05 0.00
Disk usage:     4.9GiB out of 30.9GiB
Memory usage:   185.1MiB out of 3.8GiB
Mounts:         /Users/ha/Documents/Github => /Users/ha/Documents/Github
                    UID map: 501:default
                    GID map: 20:default
- `multipass get local.driver`
qemu

**Additional context**

**Comment by sharder996** [comment]
Hi @hussainaloum, can you describe what your workflow is?

Regardless, here are a couple things that you can play with that may improve compile times for you:
1. Change the number of CPUs provisioned to the VM with `multipass set local.primary.cpus`
2. Change the amount of memory allocated to the VM with `multipass set local.primary.memory`
3. Use native mounts instead of sshfs mounts. Use `multipass mount --native <path> primary:<path>
