### ISSUE TITLE
Multipass not usable, limited, not giving warning that size is full, not giving help how to make more space, instructions are not for windows for thouse who google if its possible to change hard drive size

### ISSUE THREAD

**Issue by kangarooo** [canonical/multipass#3342]
Multipass not usable, limited, not giving warning that size is full, not giving help how to make more space, instructions are not for windows for thouse who google if its possible to change hard drive size

Hyper-v makes snapshots
While making snapshots cant change file size in hyper-v
Disbling checkpoints still tells cant edit disk because exists checkpoints
Removing checkpoints still says checkpoint exists

So people want to test ubuntu and run out of space
Help guide isnt telling what to do for windows 10 11
in multipass app commands dont work
Where to write commands?
https://multipass.run/docs/modify-an-instance

Here Commands are not fully written how to do it

https://github.com/canonical/multipass/issues/3216#issuecomment-1705466094

Here we found windows 11 makes snapshots that dont allow hyper-v to chage size. Even removing snapshots dont work.

https://github.com/canonical/multipass/issues/3216#issuecomment-1705478480

**Comment by sharder996** [comment]
Hi @kangarooo, you have found a known bug (and which has a fix submitted in the 1.13 release). You can download the RC package [here](https://github.com/canonical/multipass/releases/tag/v1.13.0-rc) and try it out if you like.

As for suggested documentation improvement, since Multipass is primarily a command line interface tool, it follows that commands are meant to be executed via command line. Having to prepend every command with a cross platform explanation of using a shell does not help in making the documentation succinct and to the point. If you have a suggestion on how we can still improve the documentation, please open a new ticket!

Since the the primary function of this ticket was to report a known and fixed bug, I am going to close this ticket. Regardless, thank you for bringing this to our attention!
