### ISSUE TITLE
Instance with too much ram 1st time shows error 2nd time doesnt show

### ISSUE THREAD

**Issue by kangarooo** [canonical/multipass#3345]
Have 16GB ram laptop
Have chrome with 20 tabs taking ram
In powershell
multipass launch --cpus 8 --disk 40G --memory 9G
From multipass task icon "open shell"
Starting.. start failed, cant close window
PS C:\Users\User> multipass start regular-meadowlark
start failed: Start-VM : 'regular-meadowlark' failed to start.
Not enough memory in the system to start the virtual machine regular-meadowlark.
Could not initialize memory: Not enough memory resources are available to complete this operation. (0x8007000E).
'regular-meadowlark' failed to start. (Virtual machine ID C986878F-3887-4B98-BBB4-1CE9256AEC02)
Not enough memory in the system to start the virtual machine regular-meadowlark with ram size 12000 megabytes.
(Virtual machine ID C986878F-3887-4B98-BBB4-1CE9256AEC02)
'regular-meadowlark' could not initialize memory: Not enough memory resources are available to complete this
operation. (0x8007000E). (Virtual machine ID C986878F-3887-4B98-BBB4-1CE9256AEC02)
At line:1 char:1
+ Start-VM -Name regular-meadowlark
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM

try 2nd time
error shows and hides. cant read 2nd time what is written since its window dissapears

**Comment by sharder996** [comment]
Hi @kangarooo, 

The error that you are seeing means that your machine does not have enough memory at the moment to start/launch the vm. Just because the amount of memory allocated to your vm is less than the amount of physical memory on your machine does not mean that you will be able to use a vm with it.

From the error you gave, it seems that you were able to create a vm with `12000M` of memory at one point, but now you are unable to start it. This means there are some extra processes running now that are using memory which were not running when you launched the vm. You can try freeing up some memory by closing some programs, or alternately, you can try modifying the amount of memory allocated to the vm (demonstrated [here](https://multipass.run/docs/modify-an-instance#heading--set-the-cpu-ram-or-disk-of-an-instance)).

As for the windows disappearing on the second attempt, I assume that you tried to shell into the instance from the GUI/tray icon. Since the vm encountered an error while starting it is expected the window closed, since the process associated with it exited.

I am going to close this issue since I don't see a issue with Multipass here, but feel free to provide more information if you are still encountered problems with this issue.
