### ISSUE TITLE
Multipass.gui throws Segmentation fault (core dumped) on wayland

### ISSUE THREAD

**Issue by nikelborm** [canonical/multipass#3444]
**Describe the bug**
I tried to run `multipass.gui`. It exited immediately with `Segmentation fault (core dumped)`

**To Reproduce**
How, and what happened?
1. Install and open latest gnome on wayland
2. Run `multipass.gui`

**Expected behavior**
I expect it to work without specifying additional env var. So it means I expect it isn't so heavily dependent on X.org when the only thing it renders is this:
![Screenshot from 2024-03-19 11-34-18](https://github.com/canonical/multipass/assets/29357907/2d1ee231-3805-4a02-9785-47f091dafd9b)

**Additional info**
I tried to run it with gdb like this:
```bash
gdb multipass.gui
> run
```
it gave me more info:
```
Thread 1 "multipass.gui" received signal SIGSEGV, Segmentation fault.
0x00005555557c49af in QHotkeyPrivateX11::nativeKeycode(Qt::Key, bool&) ()
```
Which gave me an idea that I have to run it in X mode. So I tried this:
```bash
QT_QPA_PLATFORM=xcb multipass.gui
```
Only then it started to work.

**Comment by townsend2010** [comment]
Hi @nikelborm!

Thank you for the bug report!  This is another pitfall of not running Multipass within a snap environment.  The snap will set this up for you and we really don't support running Multipass outside of a snap other than for development purposes.  Also, the `QHotKey` third party library and the use of Qt for the system tray menu will be going away in the next release of Multipass where will will be releasing a full GUI along with the system tray menu written in Flutter.

I'm going to close this since we will not be fixing this for the reasons I stated above.
