### ISSUE TITLE
Start failed: The following errors occurred • macOS 14.4.1

### ISSUE THREAD

**Issue by ghost** [canonical/multipass#3546]
**To Reproduce**
How and what happened?
1. I start ON the principle of "multipass".
2. The starting image is ""primary"**
3. I open the shell. I'm waiting for the image to launch.
4. After a while, it issues an error: "start failed: The following errors occurred" & "primary: timed out waiting for response"

**Expected behavior**
What did you expect?
1. Launch the image to connect via ssh.

**Magazines**
Attached .log

**Additional information**
- Operating system: macOS 14.4.1 (Sonoma)
- multipass --version: 1.13.1+mac
- multipassed --version: 1.13.1+mac
- QEMU is installed via HomeBrew

[multipassd.log](https://github.com/user-attachments/files/15793831/multipassd.log)

**Comment by ricab** [comment]
Hi @Ilya-Yurievich, I see that you could use the primary instance for a while and that the issue you report started after it was suspended. Shortly after, the QEMU process crashed. It is possible that the instance got corrupted. What happens if you run this command manually?

```
sudo /Library/Application\ Support/com.canonical.multipass/bin/qemu-system-aarch64 -machine virt,gic-version=3 -accel hvf -drive file=/Library/Application\ Support/com.canonical.multipass/bin/../Resources/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on -cpu host -nic vmnet-shared,model=virtio-net-pci,mac=52:54:00:a4:9c:de -device virtio-scsi-pci,id=scsi0 -drive file=/var/root/Library/Application\ Support/multipassd/qemu/vault/instances/primary/ubuntu-24.04-server-cloudimg-arm64.img,if=none,format=qcow2,discard=unmap,id=hda -device scsi-hd,drive=hda,bus=scsi0.0 -smp 1 -m 1024M -qmp stdio -chardev null,id=char0 -serial chardev:char0 -cdrom /var/root/Library/Application\ Support/multipassd/qemu/vault/instances/primary/cloud-init-config.iso -loadvm suspend -machine virt-8.2
```

Do you see a window popping up? What does it say?

Also, when did you install QEMU via HomeBrew? Before or after you first used the primary instance?

**Comment by ricab** [comment]
Closing for lack of reply.
