### ISSUE TITLE
Pink screen prompt to restart services unresponsive

### ISSUE THREAD

**Issue by ssg3d** [canonical/multipass#3669]
On:
macOS Sonoma 14.6.1
Apple M3 Pro
Multipass 1.14.0 (also reproducible on 1.13)
Ubuntu 22.04.4 LTS

Create a new ubuntu instance:
multipass launch jammy --name test --memory 16G --disk 50G --cpus 6
multipass shell test
<In the shell, do>
sudo apt update && sudo apt upgrade -y
curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -

The pink restart screen that comes up when the curl line executes is unresponsive. One has to ctrl-C to exit and redo.
I
<img width="519" alt="pinkscreen" src="https://github.com/user-attachments/assets/fb023e22-8f78-4342-9a91-8c93ad0a14ea">

**Comment by sharder996** [comment]
Hi @ssg3d, I'm not seeing anything Multipass related that is causing an issue here. I'm not willing to run unknown scripts as sudo on an instance hosted by my machine to see what you're doing. But from what I can see, your machine is connected to the internet, but might have an issue executing the script. It might have something to do with the virtual machine itself, but hard to tell. As such, I'm going to close this issue due to lack of evidence of anything Multipass related going awry.
