### ISSUE TITLE
Formatting issues on "How to modify an instance" documentation page

### ISSUE THREAD

**Issue by RVRX** [canonical/multipass#3675]
**Description of documentation issue or suggestion**
HTML tags are not escaped in this code block on [How to modify an instance](https://multipass.run/docs/modify-an-instance).
<img width="1126" alt="image" src="https://github.com/user-attachments/assets/9c684b32-395c-4d7b-99f6-944a9abac57c">

**Comment by sharder996** [comment]
@giuliazanchi Any ideas?

**Comment by giuliazanchi** [comment]
Thanks for raising this issue, it looks like something changed on our backend as this was displayed correctly at some point in the past. I’ve removed the HTML formatting tags for now, so that it’s easier to read, but I’ll keep this open and assign it to myself to explore what went wrong and find a better solution.

**Comment by petesfrench** [comment]
This issue is related to the web app, [multipass.run](https://multipass.run/), so should live under https://github.com/canonical/multipass.run/issues
@giuliazanchi @sharder996 I don't have the appropriate permissions on this repo to transfer the issue. Are you able to?

**Comment by ricab** [comment]
Hi @petesfrench, I can transfer the issue, but multipass.run is not on the available options I get. Feel free to close this one and link/copy content if you prefer.

**Comment by petesfrench** [comment]
Closing: I have made a new issue here https://github.com/canonical/multipass.run/issues/339
