### ISSUE TITLE
mount on startup sometimes fail due to the instance not being ready yet

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#425]
While we've increased the timeout for some commands, it seems we've missed some, especially around mounting:

```
$ SNAPCRAFT_BUILD_INFO=1 SNAPCRAFT_BUILD_ENVIRONMENT=multipass snapcraft
Launching a VM.
start failed: The following errors occurred:                                    
Removing "/home/multipass/project": stoi
An error occurred when trying to start the instance with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.
```

**Comment by townsend2010** [comment]
I added some simple debug to print out the timeout for the SSHSession used in sshfs_mount and it's 20 seconds.  Something else is going on here....

**Comment by Saviq** [comment]
Hmm the machine was busy (I was building three snapcraft projects at the same time) so maybe the 20s wasn't enough. I suppose if we can at least get better error output...

**Comment by Saviq** [comment]
This doesn't seem to have helped:

```
Launched: snapcraft-multipass
mount failed: The following errors occurred:
error mounting "/var/cache/snapcraft/snaps": stoi
An error occurred when trying to mount using 'multipass': returned exit code 2.
```

**Comment by Saviq** [comment]
I'm instrumenting the mount area a bit more in the hope to get more info.

**Comment by Saviq** [comment]
Aaaand so:
```
[2018-10-03T11:45:02.679] [debug] [sshfs mount] make_sftp_server; `id -u` = 
start failed: The following errors occurred:                                    
Removing "/home/multipass/project": stoi
```

**Comment by townsend2010** [comment]
This still doesn't quite make sense...the `multipass` user is valid because an ssh connection can be established using that user because the call to instantiate SSHSession succeeds.  Given that, I'm confused as to why `id -u` doesn't return anything for the current valid user?  And I'm also surprised `id -u` doesn't return an error when it can't figure out the UID of the current user.  This is strange...

Maybe we should put in some loop to try a few times in establishing a mount on start before bailing out to work through any start up races.
