### ISSUE TITLE
Transient errors when performing mounts

### ISSUE THREAD

**Issue by sergiusens** [canonical/multipass#502]
During start, I get,
    start failed: The following errors occurred: Removing "/root/project": failed to obtain exit status for remote process: 'id -ng'

Maybe mounting should be more resilient?

**Comment by Saviq** [comment]
I believe this happens when we try to mount and the VM may just not be ready yet for real (it responds to SSH, but doesn't actually allow login).

**Comment by ricab** [comment]
@sergiusens do you get this consistently in any particular setting? Do you know of a simple way to reproduce it? Thanks.

**Comment by townsend2010** [comment]
I don't think this is an issue ssh logins not being ready because other commands have already ran successfully before `id -ng` runs, like `id -nu` and 'mkdir -p` for example.

We have a default 5 second timeout waiting for the exit code, which seems like more than enough time for a command to complete in the instance and return the exit code.  So I wonder if there are some cases where the exit code is simply being lost or the callback for obtaining the exit code never runs??

**Comment by townsend2010** [comment]
After a little more looking at this code:
```
int rc{SSH_OK};
while ((std::chrono::steady_clock::now() < deadline) && rc == SSH_OK && !exit_status)
{
    rc = ssh_event_dopoll(event.get(), timeout.count());
}
```

it's also possible that `ssh_event_dopoll()` returned an error before the timeout and thus, broke out of the loop.  We should definitely check if there is an error in this case and log accordingly.

**Comment by ricab** [comment]
Good point. We would still need to check whether or not there was a timeout, because that is one of the reasons for `ssh_event_dopoll` not to return `SSH_OK`. Strangely, the [documentation](https://git.libssh.org/projects/libssh.git/tree/src/poll.c?h=libssh-0.8.0&id=d66ea0b3b100664916cbab965e79a870e31ac7fe#n868) for `ssh_event_dopoll` isn't clear about the return value when a timeout occurs. But according to the [documentation](https://git.libssh.org/projects/libssh.git/tree/src/poll.c?h=libssh-0.8.0&id=d66ea0b3b100664916cbab965e79a870e31ac7fe#n580) of `ssh_poll_ctx_dopoll`, it must return SSH_AGAIN in that case. 

Perhaps we should also log `errno` to see if it gives any useful indication. I wish there was a way to get some logging out of libssh directly.
