### ISSUE TITLE
Snap auto-upgrade shuts down vms

### ISSUE THREAD

**Issue by hatched** [canonical/multipass#55]
It appears that when snap auto-updates multipass, it also shuts down all running vms.

**Comment by Saviq** [comment]
See [the snapd forum](https://forum.snapcraft.io/t/process-lifecycle-on-snap-refresh/140) for a discussion on this - we'll have to integrate with snapd to refresh while keeping VMs around.

**Comment by townsend2010** [comment]
Ok, it looks like snapd and snapcraft support `refresh-mode` and `stop-mode` for controlling daemon behavior when updating a snap.  I'll look into these and see if I can make this better.

That said, if keeping VM's alive when the snap is updated is the goal, then it may not be be possible to do this when using Multipass's QEMU driver since the QEMU processes are direct children of the daemon and restarting the daemon will kill those processes. If we defer the daemon from restarting, then when do we restart it?

If using the libvirt driver, then is may be possible to keep VM's alive when restarting the daemons.  That's where I'll start on this:)

**Comment by townsend2010** [comment]
I'm going to reopen this issue because the snapd solution for the daemon's stop-mode doesn't quite work the way we expect it to, so we need to come up with another solution, maybe similar to how LXD does it in there snap.

**Comment by Saviq** [comment]
We now suspend and resume the instances on refresh.
