### ISSUE TITLE
failed to obtain exit status for remote process

### ISSUE THREAD

**Issue by popey** [canonical/multipass#552]
Was just trying to build a snap when:-

```
$ snapcraft 
Launching a VM.
Launched: snapcraft-olive                                                       
mount failed: The following errors occurred:
error mounting "/var/cache/snapcraft/snaps": failed to obtain exit status for remote process: 'id -u'
```

```
$ multipass version
multipass  2018.10.1
multipassd 2018.10.1
```

No idea what I did to make this happen.

**Comment by popey** [comment]
I worked around this with `snap disable multipass` / `snap enable multipass`

**Comment by townsend2010** [comment]
@popey,

Please upgrade multipass to the latest, jut released version in `beta`.  I hopefully put a fix in there that avoids this.

**Comment by townsend2010** [comment]
By the way, the new version should be 2018.12.1.  Please try it and report back if you see this again.

Thanks!

**Comment by abulka** [comment]
I just got this "failed to obtain exit status for remote process" error out of the blue.  I had been building snaps for a few days. Can no longer build snaps. I am on the latest Ubuntu 18.04. Tried rebooting Ubuntu - no help.

    $ multipass version
    multipass  v0.5
    multipassd v0.5

not sure why the versions are different to the multipass 2018.10.1 etc. numbering?

Anyway, the `snap disable multipass / snap enable multipass` trick above failed for me, because `multipassd` seemed to get hosed and I wasn't sure how to restart it: 

```
$ snapcraft
Launching a VM.
launch failed: cannot connect to the multipass socket                           
Please ensure multipassd is running and '/run/multipass_socket' is accessible
An error occurred when trying to launch the instance with 'multipass': returned exit code 2.
Ensure that 'multipass' is setup correctly and try again.

$ snap enable multipassd
snap "multipassd" is not installed
``` 

So I

    sudo snap remove multipass 
    sudo snap install multipass --beta --classic

and things seemed to start working again. But then running snapcraft I got the same error I started with:

```
Launching a VM.
Launched: snapcraft-rubber-band-async                                           
mount failed: The following errors occurred:
error mounting "/var/cache/snapcraft/snaps": failed to obtain exit status for remote process 'id -u': timeout
An error occurred when trying to mount using 'multipass': returned exit code 2. 
```

Any ideas?

**Comment by abulka** [comment]
For the benefit of this thread, `snap restart multipass` fixes this issue.
