### ISSUE TITLE
[windows] exec output not redirectable

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#577]
This is *weird*, but:

```
> multipass exec foo -- echo foo
foo
> multipass exec foo -- echo foo > foo.txt
> cat foo.txt
>
```

The output from `multipass exec` on Windows is not available for other processes to use (like even Python's subprocess doesn't get it…).

**Comment by goffinf** [comment]
Noticed this too when trying to run installation scripts for k3s on multipass. Some of those scripts rely on redirecting output from multipass exec and, because of the bug described here just hang and fail.  It is especially inconvenient on Windows since you can’t use WSL to install multipass either since that doesn’t support snap.

+1 for fixing this one.

**Comment by CalvinHartwell** [comment]
+1 for fixing this, still broken on Windows 10. 

If possible, workaround is to copy files instead. For example:
multipass transfer microk8s-vm:/var/snap/microk8s/current/credentials/client.config kubeconfig

Where microk8s-vm is the VM name. Works just like SCP syntax.
