### ISSUE TITLE
switch to core18 base

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#598]
Most of this already happens in #596, but there's a twist: any instances suspended or running on the core16 version of the snap won't be resume-able on the core18 version.

`snapd` does not give us much notice about the refresh, the only thing we could do is to fail the `pre-refresh` hook, but without [epochs' stepped upgrades](https://forum.snapcraft.io/t/epochs-stepped-upgrades/1757) that snap revision may be skipped, and in fact [would be for sure](https://forum.snapcraft.io/t/how-to-cause-a-snap-rollback/9848/4), if we failed `pre-refresh`.

The only option for safe, no-user-intervention transition would be to convert/upgrade the snapshot, but it's unclear whether that's possible.

Plan of record:
- create a `core16` snap branch and keep the latest `core16`-based release there
- add a `start` option allowing for the user to discard the snapshot
- detect the incompatible snapshot either by its metadata or the `qmp` error and mark the instance appropriately
- inform the user of the problem and how they can solve it (refresh to `core16`, shut all instances down, refresh back)

**Comment by townsend2010** [comment]
After some research on the qemu migration issue, I have found the following:

- The `machine` type is what is tripping this up.  For the `qemu` version in the current snap, it defaults to `pc-i440fx-trusty` and that is the type saved in the memory snapshot image.  However, for the version of `qemu` pulled in for the `core18` update, it defaults to `pc-i440fx-bionic`, and thus, `qemu` will not restore the memory snapshot due to the different `machine` types.
- There is no obvious way of detecting what the `machine` type is in the saved snapshot data.  It would basically require reimplementing some of the qemu internals for `loadvm` to do this.
- The `qemu-system-x86_64 -dump-vmstate <filename>` command outputs all of the essential info of the current host machine with respect to the `qemu` version.  It's a JSON file and the following object gets the `machine` type:
```
"vmschkmachine": {
    "Name": "pc-i440fx-bionic"
  }
```
- `multipassd` could run this command and parse the output to get the current `qemu` `machine` type.
- The `libvirt` driver is unaffected by this since it saves all the necessary qemu command switches in its xml file.

Here is what I'm thinking so far:

- On `suspend` of a instance, `multipassd` will run and parse the `qemu-system-x86_64 -dump-vmstate` command and save the `machine` type to the instance's JSON entry.
- On resume, ie, `start`, of the suspended instance, `multipassd` will look for this entry in the JSON file.  If found, it will use it.
- If `multipassd` does not find the entry in the JSON, it will default to using `pc-i440fx-trusty` for the `machine` type.  In the future, if the `qemu` version is updated further and the `machine` type changes, then it should be saved on a subsequent `suspend`.
- If for some reason, a user leaves an instance suspended all the way through two `qemu` upgrades, well, then they are out of luck:)

**Comment by Saviq** [comment]
@townsend2010 awesome!
