### ISSUE TITLE
Unknown command output points at /snap/multipass/$revno/bin/multipass

### ISSUE THREAD

**Issue by OddBloke** [canonical/multipass#754]
```
$ multipass lkist
Error: Unkown Command: 'lkist', see "/snap/multipass/758/bin/multipass --help"
```

This is noisy and needlessly specific IMO.

**Comment by OddBloke** [comment]
I can also imagine cases where it might cause actual problems: 

* if a refresh occurs before running the command, then it may not work
* if someone runs that command and then tries to use it from bash history some time later, it probably won't work
* if multipass weren't in classic confinement, then I think not using the `/snap/bin` wrapper might cause problems?

**Comment by Saviq** [comment]
This is a `snapd` problem, as we just use the equivalent of `$0`… We've had an issue about this already but can't find it…

**Comment by Saviq** [comment]
Right, this is `$0`, so I wonder what's best to do here. Can we even get at the original command as the user expressed it¿?

We can't `cd $SNAP/bin` as the user might have passed paths in on the command line…

**Comment by ricab** [comment]
Perhaps we could just say "try --help for more info"

**Comment by OddBloke** [comment]
One option that occurs to me: use `$0` if the running-under-snap environment variables aren't set (`SNAP_WHATEVER`), and hardcode either `/snap/bin/multipass` (or just plain `multipass`?) if you are running as a snap.

(My assumption, is that anyone who might need to run `/snap/multipass/...` is probably not the sort of person who needs a help message to point them in the right direction, so you can safely show them an incorrect path.)

(I also don't know what the snaps-in-PATH story is on distros other than Ubuntu, which might affect what you want to display when running as a snap.)

**Comment by ricab** [comment]
Hmm, multipass could be called from a faulty script or something that forwarded bad args, and I agree /paths/to/multipass are noisy here. The user just run the program, they should know how to rerun, even it it is not in the path or if it is called indirectly. So I would drop relying on $0 entirely. 

We could hardcode a program name constant and pass that to the parser (so that existing code could be reused in other programs, with different names). But again, the user should know how to rerun, so  just saying "--help" is probably enough and keeps it simpler IMO.

**Comment by ricab** [comment]
I ended up going with

`Error: Unknown Command 'asdf' (try "multipass help")`

Looks cleaner and is more consistent with other places. The string `multipass` is already hardcoded in other places (e.g. "multipass version") and can be easily extracted if/when needed.
