### ISSUE TITLE
multipass mount . foo will mount the absolute name of "." into foo

### ISSUE THREAD

**Issue by albaguirre** [canonical/multipass#84]
multipass mount . foo will mount the absolute name of "." into foo

multipass should probably mount the relative path instead

**Comment by townsend2010** [comment]
After a little discussion, if we are going to allow target path to be omitted, then I think the current behavior is correct, because the target path be the same as source path, as it states in the help.  And '.' will resolve to the full path, so care should be taken by the user that the full path on the host may not be what's expected in the VM.

Another thought is to make the target path mandatory so there is no question as what the user intends.  At any rate, I'm going to close this and we can refer to #74 about making the mount command usage more clear.
