### ISSUE TITLE
multipass doesn't support core images

### ISSUE THREAD

**Issue by popey** [canonical/multipass#87]
I'd like to test some features of Ubuntu Core inside multipass. Unfortunately `multipass find core` returns no images that I can boot in multipass. 

What are the plans to support core in multipass?

**Comment by Saviq** [comment]
We support images published on http://cloud-images.ubuntu.com/ - once core images show up there, multipass will Just Work™ with them.

**Comment by townsend2010** [comment]
With #249 now merged (and be in edge shortly), you can download core, extract it, and then do something like:

`multipass launch --image file://path/to/ubuntu-core-16-amd64.img`

We plan on also including a feature in Multipass where it will automatically extract .xz images to avoid the manual step.  See #252.

Going to close this now since we have a way to run Core now.

**Comment by townsend2010** [comment]
For completeness sake, this is how I got Core running in a Multipass instance:
```
$ wget http://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd64.img.xz
$ xz --decompress ubuntu-core-16-amd64.img.xz
$ qemu-img convert -p -O qcow2 ubuntu-core-16-amd64.img ubuntu-core-16-amd64.qcow2
$ multipass launch --image file:://ubuntu-core-16-amd64.qcow2
```

**Comment by townsend2010** [comment]
Also, `mount` will not work since we can't install sshfs in the Core instance.
