### ISSUE TITLE
Check disk space before creating instances

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#938]
We should check whether the instance we'll be trying to launch will fit in the available disk space.

**Comment by katie-knister** [comment]
Hi @Saviq! I'm interested in helping out with this. This is my first time contributing to an open source project. Do you have any tips on starting this task and/or notes on which parts of the code are relevant?

**Comment by Saviq** [comment]
Hi @katie-knister, welcome on the FOSS train, you're in for a ride :)

This is where the disk size gets validated:

https://github.com/canonical/multipass/blob/4f7ae5cac81ff379f5452a34a20a11e434d2089f/src/daemon/daemon.cpp#L317L331

Should be easy to check whether there's enough space, too.

**Comment by katie-knister** [comment]
Thank you so much for your quick and helpful response! I'll be working on this task in the next few days. Excited to get started!

**Comment by katie-knister** [comment]
Hi @Saviq , I created PR #1854 to address this issue. It uses the std::filesystem library to check for available space in the user’s directory. Do you think you could take a look and see if it’s on the right track? I am also wondering why the build check fails with including filesystem since it successfully builds locally. I’m also interested in what recommendations you have for testing this. Thank you!

**Comment by ricab** [comment]
Fixed by #1854.
