### ISSUE TITLE
Systray icon integration on Windows

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#944]
The missing bits:
- [x] icon in Start menu
- [x] autostart handling

The former should be straightforward, with the one caveat that ideally we'd check if it's already running to avoid spawning a second copy. That can come later, though.

The latter I think we can attack in steps:
1. add launching the icon to the current user's `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run` - use `--autostart` flag to tell the binary that it is autostarted
1. add a `multipass set client.gui.autostart` boolean and, if false, exit when ran with `--autostart`
1. have the above `multipass set…` add/remove the `Run` key above
1. add an option in the NSIS installer whether to add the `Run` entry at all

We can spawn separate issues from the above bits, and not all of them need to be done in v0.9.0.

**Comment by ricab** [comment]
Ouch, I missed the edit! Only saw the text now (was empty before IIRC)... Fortunately I was going in the same direction 🙂  A few comments:

- Nice thinking with the flag, but I'd propose calling it `--autostarting` instead, to better signal this is really a declaration rather than a request/option
- why the redundancy between 2 and 3, as well as these two and 4? I'd rather have a single source of truth, so just 1 and 2 all the time. That would apply nicely on other platforms too. Keeping the setting from one installation to the next would also be simpler (just keep the settings file). 
- Do we always want to use HKCU? Shouldn't that be tied to the already existing question on the scope of the PATH change? There is also SHCTX... (perhaps this can be tweaked later)

**Comment by Saviq** [comment]
As for the flag, it's quite internal, so whatever we call it is fine.
As for redundancy my thinking was that we could avoid running the binary altogether if the user disabled it. People also look into their registry and might be unhappy if they see Multipass there even if they disabled it.
We want the NSIS bit to let the user choose during install whether they want it autostarted at all or not.

**Comment by ricab** [comment]
#177 adds an item to the start menu. Not really an "icon" though I am afraid...
