### ISSUE TITLE
multipass-created parent directories for mountpoints are root-owned

### ISSUE THREAD

**Issue by OddBloke** [canonical/multipass#953]
```shell
# Create something to mount
$ mkdir example

# Launch a VM and mount our directory
$ multipass launch bionic
Launched: steady-koel
$ multipass mount example steady-koel:/home/multipass/parent/mountpoint

# Examine permissions
$ multipass exec steady-koel -- ls -ld /home/multipass/parent/mountpoint/
drwxr-xr-x 1 multipass multipass 4096 Aug 12 06:40 /home/multipass/parent/mountpoint/
$ multipass exec steady-koel -- ls -ld /home/multipass/parent/
drwxr-xr-x 3 root root 4096 Aug 12 06:36 /home/multipass/parent/
```

**Expected behaviour:** Either multipass should refuse to mount into non-existent paths, or it should create the parent paths with the same permissions as the mountpoint.

**Version**: Reproduced on both beta (1017) and edge (1041).

(Over the weekend, I wrote [a blog post](https://write.wrestle.town/oddbloke/using-multipass-to-create-a-writefreely-dev-vm) guiding people through configuring a dev VM for [WriteFreely](https://writefreely.org/) using multipass. I found a few bugs and/or rough edges that I'm filing now.)

**Comment by makspiechota** [comment]
Which path we would like to go? Refusing or creating parent with same permissions?

**Comment by Saviq** [comment]
Creating parent with same permissions for sure.

**Comment by verybigbadboy** [comment]
@Saviq I have some questions about issue:
1. if target path already exist, should we modify its permissions?
2. is there preferred way for path manipulation or it is ok to use QFileInfo/QDir?

I tried to solve this issue [commit](https://github.com/verybigbadboy/multipass/commit/94a74359b158beda6ea563a840972be6418ebd86)
I 
Currently it break some tests because test expect "set_owner_for" function call even if path already exist.
Please let me know expected behaviour so I can implement/change tests, or make better changes :)

**Comment by Saviq** [comment]
Hi @verybigbadboy, I don't think we should modify the permissions if the mountpoint exists already. But for any dirs that don't, we should change the owner.

QFileInfo / QDir is fine to use, yeah.

**Comment by verybigbadboy** [comment]
@Saviq I got you, thank you, it means I need to fix tests only
